<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}
$uacode = "";
if (substr($_SERVER["SCRIPT_NAME"], 0, 6) == '/cscap'){
    $uacode = "UA-108623031-1";
}
else if (substr($_SERVER["SCRIPT_NAME"], 0, 3) == '/td'){
    $uacode = "UA-108623031-2";
}
$ua = "";
if ($uacode != ''){
$ua = <<< EOM
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={$uacode}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{$uacode}');
</script>
EOM;
}
?>
<!-- footer -->
<footer role="contentinfo">
	<div class="container" id="iem-footer">
		<div class="row">

			<!-- footer-associates -->
			<section class="footer-associates col-sm-12 col-md-3">
				<ul>
					<li><a href="https://iastate.edu"><img src="https://cdn.theme.iastate.edu/img/isu-stacked.svg" class="wordmark-isu" alt="Iowa State University"></a></li>
					<li><a href="https://www.ag.iastate.edu">College of Ag</a></li>
					<li><a href="https://www.agron.iastate.edu">Department of Agronomy</a></li>
				</ul>
			</section>

			<!-- footer-contact -->
			<section class="footer-contact col-sm-12 col-md-3">
				<p>
					<strong>Department of Agronomy</strong><br>
					<a href="https://maps.google.com/?q=716+Farm+House+Ln+Ames,+IA+50011">716 Farm House Ln<br>
					Ames, IA 50011</a>
				</p>
				<a href="mailto:akrherz@iastate.edu">akrherz@iastate.edu</a><br>
				<a href="tel:515-294-5978">515-294-5978 phone</a> 
			</section>	

			<!-- footer-social -->
			<section class="footer-social col-sm-12 col-md-3">
				<ul class=" labeled">
				<li><a href="https://github.com/isudatateam/datateam"><span class="fa fa-external-link-square" aria-label="hidden"></span>Github</a></li>
				</ul>
			</section>	

			<!-- footer-legal -->
			<section class="footer-legal col-sm-12 col-md-3">
				<p>Copyright &copy; 2001-2017<br>
								Iowa State University<br>
								of Science and Technology<br>
								All rights reserved.</p>
				<ul>
					<li><a href="https://www.policy.iastate.edu/policy/discrimination">Non-discrimination Policy</a></li>
					<li><a href="https://www.policy.iastate.edu/electronicprivacy">Privacy Policy</a></li>
					<li><a href="https://digitalaccess.iastate.edu">Digital Access &amp; Accessibility</a></li>
				</ul>
			</section>

		</div>
	</div>
</footer>
<!-- /footer -->



    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/vendor/iastate-v2.0.1/js/vendor/bootstrap-submenu.min.js"></script>
    <script src="/vendor/iastate-v2.0.1/js/iastate.js"></script>

    <?php echo $jsextra; ?>
<?php echo $ua; ?>
  </body>
</html>
