<?php 
$jsextra = array_key_exists('jsextra', $this->vars)? $this->jsextra : '';
if (array_key_exists('iemss', $this->vars)){
	$jsextra .= <<<EOF
<script src="/vendor/openlayers/3.9.0/ol.js"></script>
<script src="/js/iemss.js"></script>
EOF;
}

?>
<div class="container" id="iem-footer">
<hr />

 <div class="pull-right">
 <form method="get" action="https://www.google.com/search" name="gsearch" 
 class="inline-form">
 <input value="mesonet.agron.iastate.edu" name="sitesearch" type="hidden" />
 
 <div class="form-group">
    <label for="inputsearch">Search Site with Google</label>
    <input type="text" class="form-control" name="q" id="inputsearch" placeholder="Enter search term">
  </div>
 </form>
 </div>

Copyright Iowa State University of Science and Technology.
<br />
 <i class="glyphicon glyphicon-wrench"></i> <a href="https://github.com/akrherz/datateam">development</a>
 
</div><!-- /.iem-footer -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
    <script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <?php echo $jsextra; ?>
  </body>
</html>
