<?php 
if (isset($this)){
	$THISPAGE = array_key_exists('thispage', $this->vars)? $this->thispage : 'xxx-xxx';
} else{
	$THISPAGE = isset($THISPAGE) ? $THISPAGE: 'xxx-xxx';
}
$_pages = Array(
	"cscap" => Array(
		"title" => "Sustainable Corn", 
		"subs" => Array(
			"base" => Array("title" => "Mainpage", "url" => "/cscap/"),
			"decagon" => Array("title" => "Decagon Data Plotting", "url" => "/cscap/plot_decagon.phtml"),
			"tileflow" => Array("title" => "Tile Flow Data Plotting", "url" => "/cscap/plot_tileflow.phtml"),
			"watertable" => Array("title" => "Water Table Data Plotting", "url" => "/cscap/plot_watertable.phtml"),
		),
	),
	"td" => Array(
		"title" => "Transforming Drainage",
		"subs" => Array(
			"base" => Array("title" => "Mainpage", "url" => "/td/"),
			"analysis" => Array("title" => "Analysis Reports", "url" => "/td/analysis/"),
			"decagon" => Array("title" => "Decagon Data Plotting", "url" => "/td/plot_decagon.phtml"),
			"nitrateload" => Array("title" => "Nitrate Load Data Plotting", "url" => "/td/plot_nitrateload.phtml"),
			"tileflow" => Array("title" => "Tile Flow Data Plotting", "url" => "/td/plot_tileflow.phtml"),
			"watertable" => Array("title" => "Water Table Data Plotting", "url" => "/td/plot_watertable.phtml"),
		),
	),
		"admin" => Array(
		"title" => "Administration",
		"subs" => Array(
			"base" => Array("title" => "Mainpage", "url" => "/admin/"),
		),
	),
);
?>
<div class="container" id="iem-header">
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="padding:0px 5px 0px 0px;"><img alt="IEM" style="height: 50px;" class="img-responsive pull-left" src="/images/logo_small.png" /></a>
	</div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" 
	href="#"> <span class="glyphicon glyphicon-home"></span> </a>
	<ul class="dropdown-menu">
		<li><a href="/">ISU Data Team</a></li>
	    <li><a href="http://sustainablecorn.org">Sustainable Corn</a></li>
		<li><a href="http://transformingdrainage.org">Transforming Drainage</a></li>
	</ul></li>
        
<?php 
$ar = preg_split('/-/', $THISPAGE);
function get_title($page){
	if (array_key_exists("icon", $page)){
		return sprintf("<div class=\"hidden-sm\">%s<b class=\"caret\"></b></div>"
				."<span class=\"glyphicon glyphicon-%s visible-sm\"></span>",
			$page["title"], $page["icon"] );
	}
	return sprintf("%s<span class=\"caret\"></span>", $page["title"]);
}

while( list($idx, $page) = each($_pages) )
{
  	echo sprintf("<li class=\"dropdown%s\">\n<a class=\"dropdown-toggle\" 
		data-toggle=\"dropdown\" href=\"#\">%s</a>\n", 
      ($ar[0] == $idx) ? " active" : "", get_title($page));

    echo "<ul class=\"dropdown-menu\">\n";
    while( list($idx2, $page2) = each($page["subs"]) )
    {
       echo sprintf("<li><a%s href=\"%s\">%s</a></li>\n", 
         ($ar[1] == $idx2 && $ar[0] == $idx) ? " class=\"active\"" : "",
           $page2["url"],  $page2["title"] );
    }
    echo "</ul>\n</li>\n";
}
  ?>
</ul>
        </div>
      </div>
    </div>
