<?php
require_once "../../../include/forms.php";

function build_treatments_ui(){
	$s = <<<EOF
<p>For sites you’ve selected, available treatments will be identified by black text; unavailable in grey.</p>
<div class="clearfix"></div>

<div class="row"><div class="col-md-6">


<div class="panel panel-default">
  <div class="panel-heading">Drainage Water Management</div>
  <div class="panel-body">

<input type="checkbox" value="Non-Drained" data-treatment="Non-Drained"
 name="treatments[]" id="Non_Drained">
<label for="Non_Drained" class="control-label">Non-Drained</label>

<input type="checkbox" value="Controlled Drainage" data-treatment="Controlled Drainage"
 name="treatments[]" id="Controlled_Drainage">
<label for="Controlled_Drainage" class="control-label">Controlled Drainage</label>

<input type="checkbox" value="Controlled Drainage with Subirrigation"
 data-treatment="Controlled Drainage with Subirrigation"
 name="treatments[]" id="Controlled_Drainage_with_Subirrigation">
<label for="Controlled_Drainage_with_Subirrigation" class="control-label">Controlled Drainage with Subirrigation</label>

<input type="checkbox" value="Free Drainage" data-treatment="Free Drainage"
 name="treatments[]" id="Free_Drainage">
<label for="Free_Drainage" class="control-label">Free Drainage</label>

<input type="checkbox" value="Surface Drainage" data-treatment="Surface Drainage"
 name="treatments[]" id="Surface_Drainage">
<label for="Surface_Drainage" class="control-label">Surface Drainage</label>

<input type="checkbox" value="Shallow Drainage" data-treatment="Shallow Drainage"
 name="treatments[]" id="Shallow_Drainage">
<label for="Shallow_Drainage" class="control-label">Shallow Drainage</label>

<input type="checkbox" value="Saturated Buffer" data-treatment="Saturated Buffer"
 name="treatments[]" id="Saturated_Buffer">
<label for="Saturated_Buffer" class="control-label">Saturated Buffer</label>

  </div>
</div>

</div><div class="col-md-6">

<div class="panel panel-default">
  <div class="panel-heading">Drainage Water Recycle</div>
  <div class="panel-body">

  <input type="checkbox" value="Non-Irrigated"
   data-treatment="Non-Irrigated"
   name="treatments[]" id="Non-Irrigated">
<label for="Non-Irrigated" class="control-label">Non-Irrigated</label>

<input type="checkbox" value="Drip Irrigation"
data-treatment="Drip Irrigation"
name="treatments[]" id="Drip Irrigation">
<label for="Drip Irrigation" class="control-label">Drip Irrigation</label>

<input type="checkbox" value="Overhead Irrigation"
data-treatment="Overhead Irrigation"
name="treatments[]" id="Overhead Irrigation">
<label for="Overhead Irrigation" class="control-label">Overhead Irrigation</label>

<input type="checkbox" value="Subsurface Irrigation"
data-treatment="Subsurface Irrigation"
name="treatments[]" id="Subsurface Irrigation">
<label for="Subsurface Irrigation" class="control-label">Subsurface Irrigation</label>

  </div>
</div>

</div></div>
EOF;
	return $s;
}

function build_agronomic_ui(){
	$s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">To Be Determined</div>
  <div class="panel-body">

<input type="checkbox" value="leaf_area_index"
 data-agronomic="leaf_area_index" name="agronomic[]" id="leaf_area_index">
<label for="leaf_area_index" class="control-label">Leaf Area Index</label>

<input type="checkbox" value="final_plant_population"
 data-agronomic="final_plant_population" name="agronomic[]" id="final_plant_population">
<label for="final_plant_population" class="control-label">Final Plant Population</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Crop Yield</div>
  <div class="panel-body">

<input type="checkbox" value="grain_moisture"
 data-agronomic="grain_moisture" name="agronomic[]" id="grain_moisture">
<label for="grain_moisture" class="control-label">Grain Moisture</label>

<input type="checkbox" value="crop_yield"
 data-agronomic="crop_yield" name="agronomic[]" id="crop_yield">
<label for="crop_yield" class="control-label">Crop Yield</label>

<input type="checkbox" value="biomass_yield"
 data-agronomic="biomass_yield" name="agronomic[]" id="biomass_yield">
<label for="biomass_yield" class="control-label">Biomass Yield</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Plant and Grain Biomass</div>
  <div class="panel-body">

<input type="checkbox" value="whole_plant_biomass"
 data-agronomic="whole_plant_biomass" name="agronomic[]" id="whole_plant_biomass">
<label for="whole_plant_biomass" class="control-label">Whole Plant Biomass</label>

<input type="checkbox" value="vegetative_biomass"
 data-agronomic="vegetative_biomass" name="agronomic[]" id="vegetative_biomass">
<label for="vegetative_biomass" class="control-label">Vegetative Biomass</label>

<input type="checkbox" value="grain_biomass"
 data-agronomic="grain_biomass" name="agronomic[]" id="grain_biomass">
<label for="grain_biomass" class="control-label">Grain Biomass</label>

<input type="checkbox" value="corn_cob_biomass"
 data-agronomic="corn_cob_biomass" name="agronomic[]" id="corn_cob_biomass">
<label for="corn_cob_biomass" class="control-label">Corn Cob Biomass</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Total Nitrogen Content</div>
  <div class="panel-body">

<input type="checkbox" value="whole_plant_total_N"
 data-agronomic="whole_plant_total_N" name="agronomic[]" id="whole_plant_total_N">
<label for="whole_plant_total_N" class="control-label">Whole Plant Total N</label>

<input type="checkbox" value="vegetative_total_N"
 data-agronomic="vegetative_total_N" name="agronomic[]" id="vegetative_total_N">
<label for="vegetative_total_N" class="control-label">Vegetative Total N</label>

<input type="checkbox" value="grain_total_N"
 data-agronomic="grain_total_N" name="agronomic[]" id="grain_total_N">
<label for="grain_total_N" class="control-label">Grain Total N</label>

<input type="checkbox" value="corn_cob_total_N"
 data-agronomic="corn_cob_total_N" name="agronomic[]" id="corn_cob_total_N">
<label for="corn_cob_total_N" class="control-label">Corn Cob Total N</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Total Carbon Content</div>
  <div class="panel-body">

<input type="checkbox" value="whole_plant_total_C"
 data-agronomic="whole_plant_total_C" name="agronomic[]" id="whole_plant_total_C">
<label for="whole_plant_total_C" class="control-label">Whole Plant Total C</label>

<input type="checkbox" value="vegetative_total_C"
 data-agronomic="vegetative_total_C" name="agronomic[]" id="vegetative_total_C">
<label for="vegetative_total_C" class="control-label">Vegetative Total C</label>

<input type="checkbox" value="grain_total_C"
 data-agronomic="grain_total_C" name="agronomic[]" id="grain_total_C">
<label for="grain_total_C" class="control-label">Grain Total C</label>

<input type="checkbox" value="corn_cob_total_C"
 data-agronomic="corn_cob_total_C" name="agronomic[]" id="corn_cob_total_C">
<label for="corn_cob_total_C" class="control-label">Corn Cob Total C</label>

  </div>
</div>

</div></div>
EOF;
	return $s;
}

function gen($ar, $label){
    $s = "";
    foreach($ar as $key => $value)
    {
        $s .= sprintf("<input type=\"checkbox\" value=\"%s\" ".
            "data-%s=\"%s\" name=\"%s[]\" id=\"%s\">".
            "<label for=\"%s\" class=\"control-label\">%s</label>",
            $key, $label, $key, $label, $key, $key, $value);
    }
    return $s;
}

function build_soil_ui(){
    $ar = Array(
        "soil_texture" => "Soil Texture",
        "percent_sand" => "Percent Sand",
        "percent_silt" => "Percent Silt",
        "percent_clay" => "Percent Clay",
    );
    $st = gen($ar, "soil");

    $ar = Array(
        "bulk_density" => "Bulk Density",
        "hydraulic_conductivity" => "Hydraulic Conductivitiy",
        "infiltration_rate" => "Infiltration Rate",
        "matric_potential" => "Matric Potential",
        "water_content" => "Water Content",
        "som" => "Soil Organic Matter",
        "ph_water" => "Water pH",
        "ph_salt" => "Salt pH",
        "lime_index" => "Lime Index",
        "neutralizable_acidity" => "Neutralizable Acidity",
        "cec" => "CEC",
        "k_saturation" => "K Saturation",
        "ca_saturation" => "Ca Saturation",
        "mg_saturation" => "Mg Saturation",
        "na_saturation" => "Na Saturation",
        "k_concentration" => "K Concentration",
        "ca_concentation" => "Ca Concentration",
        "mg_concentration" => "Mg Concentration",
        "na_concentration" => "Na Concentration",
        "k_amount" => "K Amount",
        "ca_amount" => "Ca Amount",
        "mg_amount" => "Mg Amount",
        "sar" => "SAR",
        "salinity_paste" => "Salinity Paste",
        "salinity_water" => "Salinity Water",        
    );
    $sp = gen($ar, "soil");

    $ar = Array(
        "soc" => "Soil Organic Carbon",      
    );
    $sc = gen($ar, "soil");

    $ar = Array(
        "total_N" => "Total N",
        "no3_concentration" => "N03 Concentration",
        "nh4_concentration" => "NH4 Concentration",
        "no3_amount" => "NO3 Amount",
        "nh4_amount" => "NH4 Amount",
        "p_b1_concentration" => "P B1 Concentration",
        "p_m3_concentration" => "P M3 Concentration",
        "p_b1_amount" => "P B1 Amount",
        "p_m3_amount" => "P M3 Amount",
    );
    $sn = gen($ar, "soil");

    $s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soil Texture</div>
  <div class="panel-body">
    ${st}
  </div>
</div>


</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soil Properties</div>
  <div class="panel-body">
    ${sp}
  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soil Carbon</div>
  <div class="panel-body">
    ${sc}
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Soil Nitrogen</div>
  <div class="panel-body">
    ${sn}
  </div>
</div>


</div></div>
EOF;
	return $s;
}

function build_sites(){
    $groups = build_site_groups();
    $headers = Array(
        "Saturated Buffers" => array(
            "t" => "Saturated Buffers", "color" => "#52af53"),
        "Controlled Drainage" => array(
            "t" => "Controlled Drainage", "color" => "#128be9"),
        "DW Recycle" => array(
            "t" => "Drainage Water Recycling", "color" => "#b10b4a"),
        "Other" => array(
            "t" => "Other", "color" => "#FFFFFF"),
    );
    $s = "";
    $tableheader = <<<EOM
    <table class="table table-striped table-bordered">
    <thead>
    <tr>
		<td><p><b>Research Site Code</b></p></td>
		<td><p><b>Principal Investigator</b></p></td>
		<td>
			<p><b>Research
			Site Official Name</b></p>
		</td>
		<td>
			<p><b>Institution</b></p>
		</td>
		<td>
			<p><b>One Page Summary</b></p>
		</td>
		<td nowrap>
			<p><b>Plot Map</b></p>
		</td>
		<td>
			<p><b>Photographs</b></p>
		</td>
    </tr>
    </thead>
EOM;
foreach($headers as $k => $v){
    $s .= "<div style='border-left: 10px {$v['color']} solid; padding-left: 5px;'>";
    $s .= "<h3>{$v['t']}</h3>";
    $s .= $tableheader;
    foreach($groups[$k] as $k2 => $row){
        $purl = "https://drive.google.com/drive/folders/". $row["drive_photos_folder"];
        $murl = "https://drive.google.com/drive/folders/". $row["drive_maps_folder"];
        $s .= sprintf("<tr><th>%s</th><td>%s</td><td>%s</td><td>%s</td>".
            "<td></td>".
            "<td><a href=\"%s\"><i class=\"fa fa-map\"></i> Link</a></td>".
            "<td><a href=\"%s\"><i class=\"fa fa-camera\"></i> Link</a></td></tr>\n",
                $row['siteid'], $row["lead_pi"], $row["official_farm_name"],
                $row["pi_institution"], $murl, $purl);
    }
    $s .= "</table>\n</div>\n";
}
	return $s;
}


function build_theses(){
	$pgconn = pg_connect("dbname=td host=iemdb-td.local user=nobody");
	$rs = pg_query(
        $pgconn,
        "select *, (string_to_array(authors, ' '))[1] as sauthor from theses ".
        "ORDER by sauthor, year ASC");
	$s = "\n";
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
	    $srs = "";
	    if ($row["online_source"] != "N/A"){
    	    $srs = sprintf("<a href=\"%s\" target=\"_blank\">%s</a>",
    	       $row["online_source"], $row["online_source"]);
	    }
	    $s .= sprintf("<p>%s%s %s %s %s</p>\n",
				$row['authors'], trim($row["year"]), $row['title'],
				$row["journal_or_source"], $srs);
	}
    $s .= "\n";
	return $s;
}

function cullna($val){
    if ($val == 'NA' || $val == 'na' || $val == 'N/A'){
        return '';
    }
    return $val;
}
function build_publications(){
	$pgconn = pg_connect("dbname=td host=iemdb-td.local user=nobody");
	$rs = pg_query(
        $pgconn,
        "select *, (string_to_array(authors, ' '))[1] as sauthor from ".
        "refereed_journals ORDER by sauthor, year ASC");
	$s = "\n";
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
		$strong =  ($row["open_access"] == 'Yes') ? "<strong>" : '';
		$endstrong =  ($row["open_access"] == 'Yes')? "</strong>": '';
        $s .= sprintf(
            "<p>%s %s%s %s %s %s %s <a href=\"%s\" target=\"_blank\">%s</a>".
            "%s</p>\n",
			$strong,
			$row['authors'], trim($row["year"]), $row['title'],
			$row["journal_or_source"], cullna($row["voliss"]),
		    cullna($row["pg_no."]),
			$row["online_source"], $row["online_source"], $endstrong);
	}
	$s .= "\n";
	return $s;
}

function build_site_groups(){
    // Create the groupings used within two sections
	$groups = Array();
	$pgconn = pg_connect("dbname=td host=iemdb-td.local user=nobody");
    $rs = pg_query(
        $pgconn,
        "SELECT * from meta_site_history ORDER by siteid ASC");
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
        $drp = $row["drainage_retention_practice"];
        if (! array_key_exists($drp, $groups)){
            $groups[$drp] = Array();
        }
        $groups[$drp][] = $row;
	}
    return $groups;
}

function build_sites_ui(){
    $groups = build_site_groups();
    $headers = Array(
        "Saturated Buffers" => "Saturated Buffers",
        "Controlled Drainage" => "Controlled Drainage",
        "DW Recycle" => "Drainage Water Recycling",
        "Other" => "Other",
    );
    $s = "";
	foreach($headers as $k => $v){
		$s .= "<div class=\"col-md-4\">\n";
		$s .= sprintf("<div class=\"panel panel-default\">".
  "<div class=\"panel-heading\">".
  "<input type=\"checkbox\" class=\"state-check\" value=\"%s\"> &nbsp; %s</div>".
  "<div class=\"panel-body\">\n", $k, $v);
		foreach($groups[$k] as $k2 => $v2){
			$s .= sprintf("<input type=\"checkbox\" value=\"%s\" id=\"ST%s\" ".
			    "data-state=\"%s\" name=\"sites[]\" class=\"site-check\">".
                "<label for=\"ST%s\" class=\"control-label\">%s</label>",
                $v2["siteid"], $v2["siteid"], $k, $v2["siteid"],
                $v2["siteid"]);
        }
        $s .= "</div></div></div>\n";
    }
	return $s;
}
function build_water_ui(){
    $ar = Array(
        "soil_moisture" => "Soil Moisture",
        "soil_temperature" => "Soil Temperature",
        "soil_ec" => "Soil EC",
    );
    $sm = gen($ar, "water");

    $ar = Array(
        "tile_flow" => "Tile Flow <sup>1</sup>",
        "tile_flow_filled" => "Tile Flow Filled <sup>2</sup> (recommended)",
        "discharge" => "Discharge",
        "nitrate_N_load" => "Nitrate N Load <sup>1</sup>",
        "nitrate_N_load_filled" => "Nitrate N Load Filled <sup>2</sup> (recommended)",
        "nitrate_N_removed" => "Nitrate N Removed",
    );
    $tfl = gen($ar, "water");

    $ar = Array(
        "nitrate_N_concentration" => "Nitrate N Concentration",
        "ammonia_N_concentration" => "Ammonia N Concentration",
        "total_N_filtered_concentration" => "Total N Filtered Concentration",
        "total_N_unfiltered_concentration" => "Total N Unfiltered Concentration",
        "ortho_P_filtered_concentration" => "Ortho P Filtered Concentration",
        "ortho_P_unfiltered_concentration" => "Ortho P Unfiltered Concentration",
        "total_P_filtered_concentration" => "Total P Filtered Concentration",
        "total_P_unfiltered_concentration" => "Total P Unfiltered Concentration",
        "pH" => "pH",
        "water_ec" => "Water EC",
    );
    $wq = gen($ar, "water");

    $s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soil Moisture</div>
  <div class="panel-body">
    ${sm}
  </div>
</div>


</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Tile Flow and Load</div>
  <div class="panel-body">
    ${tfl}
  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Water Quality</div>
  <div class="panel-body">
    ${wq}
  </div>
</div>


</div></div>
EOF;
    return $s;
}

function build_shm_ui(){
	$s = <<<EOF

<p>It is recommended to export all of the data here because they are supplemental
metadata that provide context to the experimental data and helps with
interpretation. For this reason, all variables are selected by default.</p>

	<div class="panel panel-default">
	<div class="panel-heading">Available Variables</div>
	<div class="panel-body">
			
	<input type="checkbox" value="SHM5" data-ipm="SHM5" name="shm[]" id="SHM5" checked="checked">
	<label for="SHM5" class="control-label">Data Dictionary</label>
	<input type="checkbox" value="SHM7" data-ipm="SHM7" name="shm[]" id="SHM7" checked="checked">
	<label for="SHM7" class="control-label">Drainage Control Structure Management</label>
	<input type="checkbox" value="SHM1" data-ipm="SHM1" name="shm[]" id="SHM1" checked="checked">
	<label for="SHM1" class="control-label">Field Operations</label>
	<input type="checkbox" value="SHM6" data-ipm="SHM6" name="shm[]" id="SHM6" checked="checked">
	<label for="SHM6" class="control-label">Notes</label>
	<input type="checkbox" value="SHM4" data-ipm="SHM4" name="shm[]" id="SHM4" checked="checked">
	<label for="SHM4" class="control-label">Plot Identifiers</label>
	<input type="checkbox" value="SHM8" data-ipm="SHM8" name="shm[]" id="SHM8" checked="checked">
	<label for="SHM8" class="control-label">Site Metadata and History</label>
			
	</div>
	</div>
EOF;
	return $s;
}

require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "Transforming Drainage Project Data Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
<style>
input[type=checkbox][disabled] + label {
    color: #ccc;
}
input { float: left;}
label { display: block !important; margin-left: 1.5em;}
</style>
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="dl.js?v=7"></script>
EOF;

$sitesui = build_sites_ui();
$treatmentui = build_treatments_ui();
$waterui = build_water_ui();
$agronomicui = build_agronomic_ui();
$soilui = build_soil_ui();
$shmui = build_shm_ui();
$publisting = build_publications();
$theseslisting = build_theses();
$sitestable = build_sites();

$wxyear1 = yearSelect2(1996, 1996, "year1", null, 2018);
$wxyear2 = yearSelect2(1996, 2018, "year2", null, 2018);
$wxdatacontent = <<<EOM
<br />
<ul class="nav nav-tabs" role="tablist">
 <li role="presentation" class="active"><a href="#wx2" aria-controls="wx2" role="tab" data-toggle="tab">Nearby Weather Station</a></li>
 <li role="presentation"><a href="#wx1" aria-controls="wx1" role="tab" data-toggle="tab">On-Site Weather</a></li>
</ul>

<div class="tab-content">

  
 <div role="tabpanel" class="tab-pane active" id="wx2">
<p>Supplementary weather data are available for Transforming Drainage research sites 
and are provided from nearby weather networks. These data are most appropriate 
to use with these research sites because of proximity. The data are collected 
from a variety of sources, including the National Climatic Data Center, 
National Weather Service, and State Climatologists with curation and 
management by Iowa Environmental Mesonet. These entities revise their 
data and will produce updated values that are reprocessed into this archive.</p>

<p>Documentation on this dataset can be found 
<a href="https://mesonet.agron.iastate.edu/info/datasets/climodat.html" target="_blank">here</a></p>

<form method="GET" id="wxform" action="https://mesonet.agron.iastate.edu/cgi-bin/request/coop.py">
<input type="hidden" name="network" value="IACLIMATE" id="network" />

<!--
select '<option value="'||a.climate_site||'">'||a.id||' ['||a.name||'] -- '||a.climate_site ||' '||b.name||'</option>' from stations a JOIN stations b on (a.climate_site = b.id) where a.network = 'TD' ORDER by a.id ASC;
-->
<p><strong>Select Research Site(s):</strong></p>
<select id="station" name="station[]" size="5" multiple="" class="select">
<option value="IA0200">IA_Boone [Private Farm at Boone County  IA] -- IA0200 AMES-8-WSW</option>
<option value="IA3487">IA_Grundy [Private Farm at Grundy County  IA] -- IA3487 GRUNDY-CENTER</option>
<option value="IA0200">IA_Hamilton1 [Private Farm at Bear Creek (Site 1)] -- IA0200 AMES-8-WSW</option>
<option value="IA0200">IA_Hamilton2 [Private Farm at Bear Creek (Site 2)] -- IA0200 AMES-8-WSW</option>
<option value="IA8806">IA_Hamilton3 [Private Farm at Hamilton County  IA] -- IA8806 WEBSTER-CITY</option>
<option value="IA0241">IA_Story1 [Private Farm at Hickory Grove] -- IA0241 ANKENY-3-S</option>
<option value="IA0200">IA_Story2 [Private Farm at Story County  IA] -- IA0200 AMES-8-WSW</option>
<option value="IA0600">IA_Tama [Private Farm at Rock Creek] -- IA0600 BELLE-PLAINE</option>
<option value="IA8688">IA_Washington [Southeast Research and Demonstration Farm (SERF)] -- IA8688 WASHINGTON</option>
<option value="IN2825">IN_Randolph [Davis Purdue Agricultural Center (DPAC)] -- IN2825 FARMLAND 5 NNW</option>
<option value="IN9430">IN_Tippecanoe [Agronomy Center for Research and Education (ACRE)] -- IN9430 WEST LAFAYETTE 6 NW</option>
<option value="MN0018">MN_Clay1 [Private Farm in Clay County  MN] -- MN0018 ADA</option>
<option value="MN0018">MN_Clay2 [Private Farm in Clay County  MN] -- MN0018 ADA</option>
<option value="MN0018">MN_Clay3 [Private Farm in Clay County  MN] -- MN0018 ADA</option>
<option value="MN8323">MN_Redwood1 [Private farm at Redwood County  MN] -- MN8323 TRACY</option>
<option value="MN8323">MN_Redwood2 [Private farm at Redwood County  MN] -- MN8323 TRACY</option>
<option value="MN8520">MN_Redwood3 [Southwest Research and Outreach Center (SWROC)] -- MN8520 VESTA</option>
<option value="MN6405">MN_Wilkin1 [Red River Valley Drainage Water Management (RRVDWM)] -- MN6405 PELICAN RAPIDS</option>
<option value="MN6405">MN_Wilkin2 [Red River Valley Drainage Water Management (RRVDWM)] -- MN6405 PELICAN RAPIDS</option>
<option value="MN6405">MN_Wilkin3 [Red River Valley Drainage Water Management (RRVDWM)] -- MN6405 PELICAN RAPIDS</option>
<option value="MO2482">MO_Knox1 [Greenley Memorial Research Center] -- MO2482 EDINA</option>
<option value="MO2482">MO_Knox2 [Greenley Memorial Research Center] -- MO2482 EDINA</option>
<option value="MO2482">MO_Knox3 [Private Farm at Bee Ridge Township] -- MO2482 EDINA</option>
<option value="MO2482">MO_Knox4 [Greenley Memorial Research Center] -- MO2482 EDINA</option>
<option value="MO8051">MO_Shelby [Greenley Memorial Research Center - The Ross Jones Farm] -- MO8051 STEFFENVILLE</option>
<option value="NC6853">NC_Washington [Tidewater Research Station] -- NC6853 PLYMOUTH 5 E</option>
<option value="ND5754">ND_Richland [Private Farm in Richland County  ND] -- ND5754 MC LEOD 3 E</option>
<option value="OH3915">OH_Auglaize1 [Private Farm in Auglaize County  OH] -- OH3915 HUNTSVILLE 3 N</option>
<option value="OH4551">OH_Auglaize2 [Private Farm in Auglaize County  OH] -- OH4551 LIMA WWTP</option>
<option value="OH1072">OH_Crawford [Private Farm in Crawford County  OH] -- OH1072 BUCYRUS</option>
<option value="OH2098">OH_Defiance1 [Private Farm in Defiance County  OH] -- OH2098 DEFIANCE</option>
<option value="OH2098">OH_Defiance2 [Wetland Reservoir Subirrigation Systems (WRSIS) Demonstration Si] -- OH2098 DEFIANCE</option>
<option value="OH1404">OH_Delaware [The Upper Big Walnut Creek (UBWC) watershed] -- OH1404 CENTERBURG 2 SE</option>
<option value="OH8822">OH_Fulton [Wetland Reservoir Subirrigation Systems (WRSIS) Demonstration Si] -- OH8822 WAUSEON WTP</option>
<option value="OH4189">OH_Hardin1 [Private Farm in Hardin County  OH] -- OH4189 KENTON</option>
<option value="OH2786">OH_Hardin2 [Private Farm in Hardin County  OH] -- OH2786 FINDLAY AP</option>
<option value="OH8822">OH_Henry [Private Farm in Henry County  OH] -- OH8822 WAUSEON WTP</option>
<option value="OH8609">OH_VanWert [Wetland Reservoir Subirrigation Systems (WRSIS) Demonstration Si] -- OH8609 VAN WERT 1 S</option>
<option value="SD1579">SD_Clay [Southeast Research Farm (SERF)] -- SD1579 CENTERVILLE 6 SE</option>
</select>

<br />
<p><strong>Select Time Period:</strong></p>

<table><tr><th></th><th>Year</th><th>Month</th><th>Day</th></tr>
<tr><td>Start:</td>
<td><select id="year1" name="year1">
<option value='1951' selected="selected">1951</option><option value='1952' >1952</option><option value='1953' >1953</option>
<option value='1954' >1954</option><option value='1955' >1955</option><option value='1956' >1956</option>
<option value='1957' >1957</option><option value='1958' >1958</option><option value='1959' >1959</option>
<option value='1960' >1960</option><option value='1961' >1961</option><option value='1962' >1962</option>
<option value='1963' >1963</option><option value='1964' >1964</option><option value='1965' >1965</option>
<option value='1966' >1966</option><option value='1967' >1967</option><option value='1968' >1968</option>
<option value='1969' >1969</option><option value='1970' >1970</option><option value='1971' >1971</option>
<option value='1972' >1972</option><option value='1973' >1973</option><option value='1974' >1974</option>
<option value='1975' >1975</option><option value='1976' >1976</option><option value='1977' >1977</option>
<option value='1978' >1978</option><option value='1979' >1979</option><option value='1980' >1980</option>
<option value='1981' >1981</option><option value='1982' >1982</option><option value='1983' >1983</option>
<option value='1984' >1984</option><option value='1985' >1985</option><option value='1986' >1986</option>
<option value='1987' >1987</option><option value='1988' >1988</option><option value='1989' >1989</option>
<option value='1990' >1990</option><option value='1991' >1991</option><option value='1992' >1992</option>
<option value='1993' >1993</option><option value='1994' >1994</option><option value='1995' >1995</option>
<option value='1996' >1996</option><option value='1997' >1997</option><option value='1998' >1998</option>
<option value='1999' >1999</option><option value='2000' >2000</option><option value='2001' >2001</option>
<option value='2002' >2002</option><option value='2003' >2003</option><option value='2004' >2004</option>
<option value='2005' >2005</option><option value='2006' >2006</option><option value='2007' >2007</option>
<option value='2008' >2008</option><option value='2009' >2009</option><option value='2010' >2010</option>
<option value='2011' >2011</option><option value='2012'>2012</option><option value='2013' >2013</option>
<option value='2014'>2014</option>
<option value='2015'>2015</option>
<option value='2016'>2016</option>
<option value='2017'>2017</option>
<option value='2018'>2018</option>
</select></td>
<td><select id="month1" name="month1">
<option value='1' selected="selected">January</option>
<option value='2' >February</option>
<option value='3' >March</option>
<option value='4' >April</option>
<option value='5' >May</option>
<option value='6' >June</option>
<option value='7' >July</option>
<option value='8' >August</option>
<option value='9' >September</option>
<option value='10' >October</option>
<option value='11' >November</option>
<option value='12' >December</option>
</select>
</td>
<td><select id="day1" name="day1">
<option value="1" selected="selected">1</option>
<option value="2" >2</option><option value="3" >3</option><option value="4" >4</option>
<option value="5" >5</option><option value="6" >6</option><option value="7" >7</option>
<option value="8" >8</option><option value="9" >9</option><option value="10" >10</option>
<option value="11" >11</option><option value="12" >12</option><option value="13" >13</option>
<option value="14" >14</option><option value="15" >15</option><option value="16" >16</option>
<option value="17" >17</option><option value="18" >18</option><option value="19" >19</option>
<option value="20" >20</option><option value="21" >21</option><option value="22" >22</option>
<option value="23" >23</option><option value="24" >24</option><option value="25" >25</option>
<option value="26" >26</option><option value="27" >27</option><option value="28" >28</option>
<option value="29" >29</option><option value="30" >30</option><option value="31" >31</option>
</select></td>
</tr>
<tr><td>End:</td>
<td><select id="year2" name="year2">
<option value='1951' >1951</option><option value='1952' >1952</option><option value='1953' >1953</option>
<option value='1954' >1954</option><option value='1955' >1955</option><option value='1956' >1956</option>
<option value='1957' >1957</option><option value='1958' >1958</option><option value='1959' >1959</option>
<option value='1960' >1960</option><option value='1961' >1961</option><option value='1962' >1962</option>
<option value='1963' >1963</option><option value='1964' >1964</option><option value='1965' >1965</option>
<option value='1966' >1966</option><option value='1967' >1967</option><option value='1968' >1968</option>
<option value='1969' >1969</option><option value='1970' >1970</option><option value='1971' >1971</option>
<option value='1972' >1972</option><option value='1973' >1973</option><option value='1974' >1974</option>
<option value='1975' >1975</option><option value='1976' >1976</option><option value='1977' >1977</option>
<option value='1978' >1978</option><option value='1979' >1979</option><option value='1980' >1980</option>
<option value='1981' >1981</option><option value='1982' >1982</option><option value='1983' >1983</option>
<option value='1984' >1984</option><option value='1985' >1985</option><option value='1986' >1986</option>
<option value='1987' >1987</option><option value='1988' >1988</option><option value='1989' >1989</option>
<option value='1990' >1990</option><option value='1991' >1991</option><option value='1992' >1992</option>
<option value='1993' >1993</option><option value='1994' >1994</option><option value='1995' >1995</option>
<option value='1996' >1996</option><option value='1997' >1997</option><option value='1998' >1998</option>
<option value='1999' >1999</option><option value='2000' >2000</option><option value='2001' >2001</option>
<option value='2002' >2002</option><option value='2003' >2003</option><option value='2004' >2004</option>
<option value='2005' >2005</option><option value='2006' >2006</option><option value='2007' >2007</option>
<option value='2008' >2008</option><option value='2009' >2009</option><option value='2010' >2010</option>
<option value='2011' >2011</option><option value='2012'>2012</option><option value='2013' >2013</option>
<option value='2014'>2014</option>
<option value='2015'>2015</option>
<option value='2016'>2016</option>
<option value='2017'>2017</option>
<option value='2018' selected="selected">2018</option>
</select></td>
<td><select id="month2" name="month2">
<option value='1' selected="selected">January</option>
<option value='2' >February</option>
<option value='3' >March</option>
<option value='4' >April</option>
<option value='5' >May</option>
<option value='6' >June</option>
<option value='7' >July</option>
<option value='8' >August</option>
<option value='9' >September</option>
<option value='10' >October</option>
<option value='11' >November</option>
<option value='12' >December</option>
</select></td>
<td><select id="day2" name="day2">
<option value="1" selected="selected">1</option>
<option value="2" >2</option><option value="3" >3</option><option value="4" >4</option>
<option value="5" >5</option><option value="6" >6</option><option value="7" >7</option>
<option value="8" >8</option><option value="9" >9</option><option value="10" >10</option>
<option value="11" >11</option><option value="12" >12</option><option value="13" >13</option>
<option value="14" >14</option><option value="15" >15</option><option value="16" >16</option>
<option value="17" >17</option><option value="18" >18</option><option value="19" >19</option>
<option value="20" >20</option><option value="21" >21</option><option value="22" >22</option>
<option value="23" >23</option><option value="24" >24</option><option value="25" >25</option>
<option value="26" >26</option><option value="27" >27</option><option value="28" >28</option>
<option value="29" >29</option><option value="30" >30</option><option value="31" >31</option>
</select></td>
</tr>
</table>

<p><strong>Select Data Variables</strong>:
<br /><i>Date and Day of Year are included automatically in the export. 
To select multiple data, hold CTRL key down while selecting options here.</i>
<br /><select size=5 name="vars[]" MULTIPLE class="select">0
  <option value="high">Variable: High Air Temperature [F]</option>
  <option value="highc">Variable: High Air Temperature [C]</option>
  <option value="low">Variable: Low Air Temperature [F]</option>
  <option value="lowc">Variable: Low Air Temperature [C]</option>
  <option value="precip">Variable: Precipitation (rain+melted snow) [inch]</option>
  <option value="precipmm">Variable: Precipitation (rain+melted snow) [mm]</option>
  <option value="merra_srad">Variable: Solar Radiation from MERRA (shortwave down at ground) [MJ m-2 dy-1]</option>
  <option value="gdd_50_86">Computed: Growing Degree Days (base=50,max=86) [F]</option>
</select></p>

<p><strong>Optional: Specialized Model Formats for Export</strong>:
<br /><i>These are specialized formats typically used for modelling and
their choice dictates the variables to be included.</i>
<br />
<select size="5" name="model">
  <option value="apsim">Model: APSIM MET File</option> 
  <option value="century">Model: Century (Monthly Format)</option> 
  <option value="daycent">Model: DailyDayCent (no extra drivers)</option> 
  <option value="dndc">Model: DNDC</option> 
  <option value="salus">Model: SALUS</option> 
  <option value="swat">Model: SWAT (daily precip and temperature)</option> 
</select></p>

<input type="hidden" name="what" value="download" />

<p><strong>Data Delimitation:</strong>
<br />How shall the output values be separated?
<br><select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select></p>

<p>The downloaded data file name will contain the weather station identifiers
if you request data from 9 or less sites.  For requests over 9 sites,
the filename will simply be "changeme". Refer to the drop-down above for reminder as to 
which site it corresponds with.</p>

<p><input type="submit" value="Request Data" /></p>
</form>
  </div><!--./wx2-->

 <div role="tabpanel" class="tab-pane" id="wx1">

<p>On-site weather stations existed at some research sites to provide finer
resolution weather data as compared to the networked weather data which can
be a mile or more away. This on-site weather data is especially valuable for
precipitation amounts as that will vary more spatially than temperature or
wind.</p>

<p>On-site weather stations tend to be less robust of instrumentation however
than the weather data included under the first tab. It is recommended to use
this on-site data as a secondary data set to refine the networked data. It
is expected that the temperature and wind values will be near identical
between the stations but the precipitation amounts will vary.</p>

<form method="GET" id="wxform2" action="wxdl.py">
<!--
with data as (select siteid, min(date), max(date) from weather_data group by siteid) select '<option value="'||siteid ||  '">'|| siteid || ' '||' ('|| min ||' to '|| max ||')</option>' as d
 from data ORDER by d;
-->
<p><strong>Select Research Site(s):</strong>
<br />
<select name="stations" size="5" multiple="" class="select">
<option value="IA_Boone">IA_Boone  (2016-06-10 to 2018-12-31)</option>
<option value="IA_Grundy">IA_Grundy  (2016-01-01 to 2018-12-31)</option>
<option value="IA_Hamilton1">IA_Hamilton1  (2011-06-06 to 2018-12-31)</option>
<option value="IA_Hamilton2">IA_Hamilton2  (2016-01-01 to 2018-12-31)</option>
<option value="IA_Hamilton3">IA_Hamilton3  (2013-06-07 to 2018-12-31)</option>
<option value="IA_Story1">IA_Story1  (2016-06-14 to 2018-12-31)</option>
<option value="IA_Story2">IA_Story2  (2005-01-01 to 2013-04-30)</option>
<option value="IA_Tama">IA_Tama  (2016-01-01 to 2018-12-31)</option>
<option value="IA_Washington">IA_Washington  (2007-01-01 to 2018-12-31)</option>
<option value="IN_Randolph">IN_Randolph  (2005-10-01 to 2017-12-31)</option>
<option value="IN_Tippecanoe">IN_Tippecanoe  (1996-07-01 to 2018-12-31)</option>
<option value="MN_Clay1">MN_Clay1  (2014-01-01 to 2018-12-31)</option>
<option value="MN_Clay2">MN_Clay2  (2013-01-01 to 2018-12-31)</option>
<option value="MN_Clay3">MN_Clay3  (2012-04-27 to 2012-08-09)</option>
<option value="MN_Redwood1">MN_Redwood1  (2011-10-21 to 2015-12-31)</option>
<option value="MN_Redwood3">MN_Redwood3  (2015-01-01 to 2017-12-31)</option>
<option value="MO_Knox1">MO_Knox1  (2010-01-01 to 2017-12-31)</option>
<option value="MO_Knox2">MO_Knox2  (2015-01-01 to 2018-12-31)</option>
<option value="MO_Knox3">MO_Knox3  (2010-06-28 to 2013-12-31)</option>
<option value="MO_Knox4">MO_Knox4  (2010-01-01 to 2013-12-31)</option>
<option value="MO_Shelby">MO_Shelby  (2002-01-01 to 2018-12-31)</option>
<option value="NC_Washington">NC_Washington  (2007-01-01 to 2012-12-31)</option>
<option value="ND_Richland">ND_Richland  (2015-05-23 to 2018-11-07)</option>
<option value="OH_Auglaize1">OH_Auglaize1  (2008-01-01 to 2011-09-30)</option>
<option value="OH_Auglaize2">OH_Auglaize2  (2008-10-12 to 2014-10-29)</option>
<option value="OH_Crawford">OH_Crawford  (2008-10-08 to 2010-12-16)</option>
<option value="OH_Defiance1">OH_Defiance1  (2008-01-03 to 2011-09-30)</option>
<option value="OH_Defiance2">OH_Defiance2  (1999-04-07 to 2009-05-21)</option>
<option value="OH_Delaware">OH_Delaware  (2005-01-01 to 2012-12-31)</option>
<option value="OH_Fulton">OH_Fulton  (2004-04-01 to 2011-03-02)</option>
<option value="OH_Hardin1">OH_Hardin1  (2008-10-13 to 2010-12-16)</option>
<option value="OH_Hardin2">OH_Hardin2  (2008-01-01 to 2009-12-31)</option>
<option value="OH_Henry">OH_Henry  (2008-01-01 to 2010-12-31)</option>
<option value="OH_VanWert">OH_VanWert  (2003-09-14 to 2009-11-10)</option>
<option value="SD_Clay">SD_Clay  (2015-01-01 to 2017-12-31)</option>
</select>
</p>
<p><strong>Select Time Period:</strong>

<table><tr><th></th><th>Year</th><th>Month</th><th>Day</th></tr>
<tr><td>Start:</td>
<td>{$wxyear1}</td>
<td><select id="month1" name="month1">
<option value='1' selected="selected">January</option>
<option value='2' >February</option>
<option value='3' >March</option>
<option value='4' >April</option>
<option value='5' >May</option>
<option value='6' >June</option>
<option value='7' >July</option>
<option value='8' >August</option>
<option value='9' >September</option>
<option value='10' >October</option>
<option value='11' >November</option>
<option value='12' >December</option>
</select>
</td>
<td><select id="day1" name="day1">
<option value="1" selected="selected">1</option>
<option value="2" >2</option><option value="3" >3</option><option value="4" >4</option>
<option value="5" >5</option><option value="6" >6</option><option value="7" >7</option>
<option value="8" >8</option><option value="9" >9</option><option value="10" >10</option>
<option value="11" >11</option><option value="12" >12</option><option value="13" >13</option>
<option value="14" >14</option><option value="15" >15</option><option value="16" >16</option>
<option value="17" >17</option><option value="18" >18</option><option value="19" >19</option>
<option value="20" >20</option><option value="21" >21</option><option value="22" >22</option>
<option value="23" >23</option><option value="24" >24</option><option value="25" >25</option>
<option value="26" >26</option><option value="27" >27</option><option value="28" >28</option>
<option value="29" >29</option><option value="30" >30</option><option value="31" >31</option>
</select></td>
</tr>
<tr><td>End:</td>
<td>{$wxyear2}</td>
<td><select id="month2" name="month2">
<option value='1'>January</option>
<option value='2' >February</option>
<option value='3' >March</option>
<option value='4' >April</option>
<option value='5' >May</option>
<option value='6' >June</option>
<option value='7' >July</option>
<option value='8' >August</option>
<option value='9' >September</option>
<option value='10' >October</option>
<option value='11' >November</option>
<option value='12' selected="selected">December</option>
</select></td>
<td><select id="day2" name="day2">
<option value="1">1</option>
<option value="2" >2</option><option value="3" >3</option><option value="4" >4</option>
<option value="5" >5</option><option value="6" >6</option><option value="7" >7</option>
<option value="8" >8</option><option value="9" >9</option><option value="10" >10</option>
<option value="11" >11</option><option value="12" >12</option><option value="13" >13</option>
<option value="14" >14</option><option value="15" >15</option><option value="16" >16</option>
<option value="17" >17</option><option value="18" >18</option><option value="19" >19</option>
<option value="20" >20</option><option value="21" >21</option><option value="22" >22</option>
<option value="23" >23</option><option value="24" >24</option><option value="25" >25</option>
<option value="26" >26</option><option value="27" >27</option><option value="28" >28</option>
<option value="29" >29</option><option value="30" >30</option><option value="31" selected="selected">31</option>
</select></td>
</tr>
</table>

</p>
<!--
<p><strong>Select Data Variables:</strong>
<br /><i>Date and Day of Year are included automatically in the export. 
To select multiple data, hold CTRL key down while selecting options here.</i>
<br /><select size=5 name="vars" MULTIPLE class="select">0
  <option value="high">Variable: High Air Temperature [F]</option>
  <option value="highc">Variable: High Air Temperature [C]</option>
  <option value="low">Variable: Low Air Temperature [F]</option>
  <option value="lowc">Variable: Low Air Temperature [C]</option>
  <option value="precip">Variable: Precipitation (rain+melted snow) [inch]</option>
  <option value="precipmm">Variable: Precipitation (rain+melted snow) [mm]</option>
  <option value="srad">Variable: Solar Radiation [MJ m-2 dy-1]</option>
  <option value="gdd_50_86">Computed: Growing Degree Days (base=50,max=86) [F]</option>
</select>
</p>
-->
<br />

<br /><input type="submit" value="Request Data">
</p>

</form>

 </div><!--./wx1-->


</div><!--./tab-content-->
EOM;

$t->content = <<<EOF

<br />

 <!-- Nav tabs -->
  <ul class="nav nav-tabs maintabs" role="tablist">
    <li role="presentation"><a href="/td/" role="tab"><i class="fa fa-home"></i></a></li>
    <li role="presentation" class="active"><a href="#sites" aria-controls="sites" role="tab" data-toggle="tab">Research Sites</a></li>
    <li role="presentation"><a href="#data" aria-controls="data" role="tab" data-toggle="tab">Data</a></li>
    <li role="presentation"><a href="#datavers" aria-controls="data" role="tab" data-toggle="tab">Data Version</a></li>
    <li role="presentation"><a href="#wxdata" aria-controls="data" role="tab" data-toggle="tab">Weather Data</a></li>
    <li role="presentation"><a href="#wdata" aria-controls="data" role="tab" data-toggle="tab">Data Visualization</a></li>
    <li role="presentation"><a href="#pubs" aria-controls="pubs" role="tab" data-toggle="tab">Publications</a></li>
  </ul>
  
<div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="data">
    
<form method="POST" action="dl.py" id="mainform">
<div class="btn-group fauxtabs" role="group" aria-label="Pages">
  <button type="button" class="btn btn-primary" id="sites-btn">Sites</button>
  <button type="button" class="btn btn-default" id="treatments-btn">Treatments</button>
  <button type="button" class="btn btn-default" id="water-btn">Water</button>
  <button type="button" class="btn btn-default" id="agronomic-btn">Agronomic</button>
  <button type="button" class="btn btn-default" id="soil-btn">Soil</button>
  <button type="button" class="btn btn-default" id="shm-btn">Management and Metadata</button>
  <button type="button" class="btn btn-default" id="option-btn">Export Options</button>
</div>

<div id="sites-ui" style="display: block;">
<div class="pull-right">
<button id="sites-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>

<p>This download tool will auto-populate options in the following tabs based on the research sites selected below. 
It is recommended to “Select All” sites if you want to retain the most options moving forward.</p>
{$sitesui}
</div>

<div id="treatments-ui" style="display: none;">
<div class="pull-right">
  <button id="treatments-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>

{$treatmentui}
</div>

<div id="water-ui" style="display: none;">
<div class="pull-right">
<button id="water-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>

<p>This download tool will auto-populate options in the following tabs based on the research sites selected below. 
It is recommended to “Select All” sites if you want to retain the most options moving forward.</p>

{$waterui}

<p>
<sup>1</sup> Data are provided for each in-field collection. However, based on equipment setup, some sites collect a composite sample which represents the sum for a series of days while other sites collect daily measurements.
</p>
<p>
<sup>2</sup> Data are provided on a daily basis with interpolations performed when needed based on gap-filling methods developed specifically by the Transforming Drainage team. This is the RECOMMENDED data to use unless you are familiar with interpolating time-series water data.
</p>

</div>

<div id="agronomic-ui" style="display: none;">
<div class="pull-right">
  <button id="agronomic-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>

<p>For sites and treatments you’ve selected, available agronomic data will be identified by black text; 
unavailable in grey. The usage of abbreviations <i>C</i>
and <i>N</i> below denote <i>carbon</i> and <i>nitrogen</i> respectively.</p>
{$agronomicui}
</div>

<div id="soil-ui" style="display: none;">
<div class="pull-right">
  <button id="soil-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>
<p>For sites and treatments you’ve selected, available soil data will be identified by black text; 
unavailable in grey.</p>
<div class="clearfix"></div>

{$soilui}
</div>

<div id="shm-ui" style="display: none;">
<div class="pull-right">
  <button id="shm-selectall" type="button" class="btn btn-default sa"><i class="fa fa-check"></i> Select All</button>
</div>
<div class="clearfix"></div>

{$shmui}
</div>

<div id="option-ui" style="display: none;">


<div class="form-group">
    <label for="dlimit">How to handle values below detection limit:</label>
<select name="detectlimit" class="form-control" id="dlimit">
	<option value="1">Keep them as is, presented as "&lt; LOD"</option>
	<option value="2">Divide the LOD value by two</option>
	<option value="3">Divide the LOD value by square root of two</option>
	<option value="4">Omit all occurrences and replace as missing</option>
</select>
</div>

<div class="form-group">
    <label for="missingvalue">How to represent missing values:</label>
<select name="missing" class="form-control" id="missingvalue">
	<option value="M">M</option>
	<option value="N/A">N/A</option>
	<option value="NaN">NaN</option>
	<option value="NULL">NULL</option>
	<option value=" ">((blank space))</option>
	<option value=".">.</option>
	<option value="-999">-999</option>
    <option value="__custom__">Custom Value</option>
</select>
</div>

<div class="form-group" id="missingvalue_opt" style="display: none;">
    <label for="missingcustom">Enter Custom Missing Value:</label>
    <input type="text" name="custom_missing" id="missingcustom" class="form-control">
</div>

<div class="form-group">
    <label for="myemail">Enter Email Address:</label>
    <input type="text" name="email" id="myemail" placeholder="joeuser@iastate.edu" class="form-control" aria-describedby="helpEmailBlock">
    <label for="myemail2">Verify Email Address:</label>
    <input type="text" name="email2" id="myemail2" placeholder="joeuser@iastate.edu" class="form-control" aria-describedby="helpEmailBlock">
<span id="helpEmailBlock" class="help-block">You will be emailed the exported data file once generated.</span>
</div>
<br class="clearfix" />

<h4>Transforming Drainage Project Research Data (USDA-NIFA Award No. 2015-68007-23193) Usage Agreement</h4>
<blockquote>
<p>Please reference this data set in publications as:</p>

<p>Chighladze, G., L.J. Abendroth, D. Herzmann, M. Helmers, L. Ahiablame, 
B. Allred, L. Bowling, L. Brown, N. Fausey, J. Frankenberger, D. Jaynes, 
X. Jia, J. Kjaersgaard, K. King, E. Kladivko, K. Nelson, L. Pease, 
B. Reinhart, J. Strock, and M. Youssef 2021. Transforming Drainage Project Research Data 
(USDA-NIFA Award No. 2015-68007-23193). National Agricultural Library - 
ARS - USDA. [doi TBD]</p>

<p>You are encouraged to contact the Transforming Drainage Project personnel 
listed above to ensure proper data interpretation and may also consider 
co-authoring with them. You shall have no claim of ownership to any 
intellectual property rights in any part of the data, content, functions, 
features, code, data exploration tools, logos or other intellectual 
property comprising this database.</p>

<p>The coauthors individually and the Transforming Drainage Project 
collectively shall NOT be responsible or liable for the accuracy, 
reliability and completeness of any information included in the 
database nor the suitability of its application for any particular purpose. 
Data users are encouraged to notify the coauthors regarding data quality 
and other issues concerning the data, tools, and functionality of this 
website. Contact <a href="mailto:isudatateam@iastate.edu">isudatateam@iastate.edu</a>
with any questions or concerns 
regarding usage and application of the data available at this site.
</p>
</blockquote>

<p>
<input id="agreewithterms" type="checkbox" name="agree" value="AGREE"> I agree
 with the above terms of usage.
</p>


<div class="alert alert-info" role="alert" id="dlmsg" style="display: none;">
<strong>Thank you</strong>: Your request has been sent to the server for
processing.  In a few minutes, you should get a message here that your request
has been processed and an email will be delivered to your address with details
on how to download your data file. Large data requests may result in a processing
timeout shown, but an email will still be delivered with the data.</div>

<div class="alert alert-info" role="alert" id="dlmsg2" style="display: none;">
<strong>Completed</strong>: Please check your email for download information!</div>

<div id="proceed" style="display: none;">
  <p><input type="submit" value="Proceed with Download"></p>
</div>
	
</div>
<br clear="both" />
<div class="pull-right">
<button id="prev-btn" type="button" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Previous</button>
<button id="next-btn" type="button" class="btn btn-default">Next <i class="glyphicon glyphicon-arrow-right"></i></button>
</div>
</form>
		</div>
		<div role="tabpanel" class="tab-pane active" id="sites">

<div class="row"><div class="col-md-6">
<p><img src="/images/tdsites.png" class="img img-responsive" alt="Transforming Drainage Sites">

<br />View the <a href="https://drive.google.com/drive/folders/123nkLLWggCyXvdU37S9R0W91mDOw-u7Z" target="_blank">Google Map</a> with plot dimensions
and infrastructure highlighted. Some sites are not included in the Google map
because of privacy for research located on farmer fields.
</p>
</div></div>

<br />

    {$sitestable}


		</div>
		<div role="tabpanel" class="tab-pane" id="pubs">

<br />

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#p1" aria-controls="p1" role="tab" data-toggle="tab">Refereed Journals</a></li>
    <li role="presentation"><a href="#p2" aria-controls="p2" role="tab" data-toggle="tab">Thesis and Dissertations</a></li>
  </ul>
  
<div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="p1">
<p><blockquote>Articles with open access availability are <strong>in bold</strong>.
These do not require a subscription to the journal to access. For individuals 
without accessibility to certain journals, contact 
<a href="mailto:isudatateam@iastate.edu">isudatateam@iastate.edu</a> 
for requests to articles below that are subscription-only.</blockquote></p>

{$publisting}
    </div>
    
    <div role="tabpanel" class="tab-pane" id="p2">
<p><blockquote>Several graduate students were supported by and contributed to 
the scientific discoveries and publications of the Transforming Drainage team. 
Their theses and dissertations are provided here via links to their major 
University library.</blockquote></p>

{$theseslisting}
    </div>
    
    <div role="tabpanel" class="tab-pane" id="p3">


    </div>
</div>

		</div>
    <div role="tabpanel" class="tab-pane" id="wdata">

<p>Reference this map of research sites to identify sites and practices of 
interest for plotting in the visualization tools below. Not every measurement 
is available for plotting given site differences.</p>

<iframe src="https://www.google.com/maps/d/embed?mid=1Ubw9c2nAILMhNFclLT0IxNI1yFw&amp;z=5&amp;ll=42.62%2C-88.72" width="640" height="480"></iframe>

<p>Measurements include:<br />
<ul>
<li>Tile Flow (coming soon)</li>
<li><a href="/td/plot_nitrateload.phtml" target="_blank">Nitrate Load</a></li>
<li>Water Table Depth (coming soon)</li>
<li>Water Quality (coming soon)</li>
<li>Soil Moisture and Temperature (coming soon)</li>
</ul>

<p>Project-wide tools are also available at 
<a href="https://transformingdrainage.org/tools/" target="_blank">Transforming Drainage Tools</a>.
You will find geospatial tools for identifying areas where these
drainage practices may be successful as well as calculators to determine 
installation specifications and effectiveness of practices.</p>

    </div><!-- ./wdata -->

    <div role="tabpanel" class="tab-pane" id="datavers">
<br />
    <p>Research data were published at USDA National Agricultural Library Ag Data
Commons in Feb 2021 at doi:############. Additional data or edits made to
that dataset will be listed here in the future. Any additions or edits are
expected to be minor, if any.</p>
    </div><!-- ./datavers -->

    <div role="tabpanel" class="tab-pane" id="wxdata">
    {$wxdatacontent}
    </div>
</div>

</div>

</div>    

<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/tdbanner.png" class="img img-responsive">
		
EOF;
$t->render('single.phtml');

?>
