<?php 
// require_once "../../include/require_auth.php";
require_once "../../include/myview.php";

$t = new MyView();
$t->title = "CSCAP Data Portal";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Sustainable Corn Coordinated Agricultural Project Team Research Data</h3>

<p><img src="/images/team.jpg" class="img img-responsive" alt="2015 CSCAP Team">
</p>

<p>This website contains biophysical research data measured across a set of 
experiments carried out by the Cropping Systems Coordinated Agricultural 
Project (CSCAP): Climate Change, Mitigation, and Adaptation in Corn-based 
Cropping Systems; or Sustainable Corn CAP.
</p>

<p>The Sustainable Corn CAP was a transdisciplinary team funded by the 
United States Department of Agriculture, National Institute of Food and 
Agriculture (USDA-NIFA, Award No. 2011-68002-30190). The team spanned 9 states, 
11 institutions, and 140 members with funding from 2011-2016 with 
Dr. Lois Wright Morton as project director and 
Lori Abendroth as project manager.
</p>

<p>The team assessed the environmental and social economic impacts of climate 
variability on corn-based cropping systems. The project focused on ways to 
equip farmers with the practices that would build resiliency of the systems 
to increasing weather variability while maintaining crop yields and reducing 
negative environmental impacts.
</p>

<p>The Sustainable Corn CAP team's annual reports, proposals, technical 
reports, and publications are available at
<a href="http://lib.dr.iastate.edu/sustainablecorn/" target="_blank">http://lib.dr.iastate.edu/sustainablecorn/</a>. 
The Sustainable Corn CAP data is also described and available at the USDA National Agricultural Library Ag Data Commons (url pending).
</p>


<p>&nbsp;</p>
<div class="clearfix"></div>
<div class="pull-right">
<a class="btn btn-primary" href="/cscap/dl/"><i class="fa fa-arrow-right"></i> Download Research Data</a>
</div>

<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/logos/web_logos.png" class="img img-responsive">



EOF;
$t->render('single.phtml');

?>
