<?php
include_once "../../include/forms.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC::NE';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from tileflow_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
		"BRADFORD.A::101"=>"BRADFORD.A 101 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::102"=>"BRADFORD.A 102 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::104"=>"BRADFORD.A 104 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::105"=>"BRADFORD.A 105 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::201"=>"BRADFORD.A 201 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::202"=>"BRADFORD.A 202 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::203"=>"BRADFORD.A 203 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::204"=>"BRADFORD.A 204 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::301"=>"BRADFORD.A 301 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::302"=>"BRADFORD.A 302 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::303"=>"BRADFORD.A 303 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::304"=>"BRADFORD.A 304 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::401"=>"BRADFORD.A 401 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::403"=>"BRADFORD.A 403 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::404"=>"BRADFORD.A 404 (2013-05-12 to 2015-12-11) [943 days]",
		"BRADFORD.A::405"=>"BRADFORD.A 405 (2013-05-12 to 2015-12-11) [943 days]",
		"GILMORE::3.1"=>"GILMORE 3.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::3.2"=>"GILMORE 3.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::4.1"=>"GILMORE 4.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::4.2"=>"GILMORE 4.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::6.2"=>"GILMORE 6.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::7.3"=>"GILMORE 7.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::9.3"=>"GILMORE 9.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::11.1"=>"GILMORE 11.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::11.2"=>"GILMORE 11.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::12.2"=>"GILMORE 12.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::12.3"=>"GILMORE 12.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::14.1"=>"GILMORE 14.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::16.2"=>"GILMORE 16.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::16.3"=>"GILMORE 16.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::17.1"=>"GILMORE 17.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::17.3"=>"GILMORE 17.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::19.2"=>"GILMORE 19.2 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::19.3"=>"GILMORE 19.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::21.3"=>"GILMORE 21.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::22.1"=>"GILMORE 22.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::22.3"=>"GILMORE 22.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::23.1"=>"GILMORE 23.1 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::24.3"=>"GILMORE 24.3 (2011-04-05 to 2015-12-11) [1711 days]",
		"GILMORE::26.2"=>"GILMORE 26.2 (2011-04-05 to 2015-12-11) [1711 days]",
 "DPAC::NE"=>"DPAC NE (2011-12-31 to 2015-11-17) [1417 days]",
 "DPAC::NW"=>"DPAC NW (2011-12-31 to 2015-11-17) [1417 days]",
 "DPAC::SE"=>"DPAC SE (2011-12-31 to 2015-11-17) [1417 days]",
 "DPAC::SW"=>"DPAC SW (2011-12-31 to 2015-11-17) [1417 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'2' => 'Monthly Totals',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_tileflow.py?site=%s&date=%s&days=%s&ptype=%s&view=%s", 
		$site, $date, $days, $ptype, $view);
	$uri = sprintf("http://iem.local/cscap/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /cscap/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("tileflow_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

echo <<<EOF
<html lang='en'>
<head>
<link href="/vendor/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/bootstrap-override.css" rel="stylesheet">
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />  
<title>CSCAP Tileflow Data Plotting/Download</title>
<style>
select {
  color: #000;
}
</style>
</head>
<body>

<h3>CSCAP Tile Flow Data Plotting/Download</h3>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site: (<i>currently, all plots at site are shown on the graph)</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View Option</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE         INTERVAL
[IA] GILMORE      Varies     n=5 years; 2011 to 2015
[IN] DPAC         Varies     n=5 years; 2011 to 2015
[MO] BRADFORD.A   Varies     n=3 years; 2013 to 2015
</pre></p>

<h3>Notes</h3>

<ul>
 <li></li>
</ul>

<script src="/vendor/jquery/1.11.3/jquery-1.11.3.min.js"></script>
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.0/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 1, 1),
		maxDate: new Date(2016, 1, 1)});		
});
		
</script>
</body>
</html>
EOF;
?>