<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, min(date(valid)),
 max(date(valid)) from watertable_data 
 WHERE valid >= '2011-01-01' GROUP by uniqueid)
 SELECT '"'||uniqueid || '"=>"' || uniqueid || 
 ' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
 "DPAC"=>"DPAC (2011-01-01 to 2015-12-03) [1797 days]",
 "SERF"=>"SERF (2011-01-01 to 2015-12-31) [1825 days]",
 "STJOHNS"=>"STJOHNS (2011-01-13 to 2015-11-20) [1772 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_watertable.py?site=%s&date=%s&days=%s&ptype=%s&view=%s", 
		$site, $date, $days, $ptype, $view);
	$uri = sprintf("http://datateam.local/cscap/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /cscap/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("watertable_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>

EOF;
}

$t = new MyView();
$t->thispage = "cscap-watertable";
$t->title = "CSCAP Water Table Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" /> 
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.4/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "watertable_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "depth_mm";
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 0, 1),
		maxDate: new Date(2016, 1, 1)});		
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<p>&nbsp;</p>

<h3>Water Table Data Plotting/Download</h3>

<p>Water Table Depth data included in this visualization and aggregation tool are associated with two
USDA-NIFA funded projects: "Cropping Systems Coordinated Agricultural Project: Climate Change,
Mitigation, and Adaptation in Corn-based Cropping Systems." (Award No. 2011-68002-30190) and
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

<p>By using this tool, you agree to the 
<a href="/cscap/usage.phtml" target="_blank">data usage agreement</a>.</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site: (<i>currently, all plots at site are shown on the graph)</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View and Download Options</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE       INTERVAL  
[IA] SERF       60 minute  n=5 years; 2011 to 2015
[IN] DPAC       60 minute  n=10 years; 2006 to 2015
[OH] STJOHNS    60 minute  n=5 years; 2011 to 2015
</pre></p>
EOF;
$t->render('full.phtml');
?>
