<?php 
// require_once "../../include/require_auth.php";
require_once "../../include/myview.php";

$t = new MyView();
$t->title = "Sustainable Corn Data Usage Agreement";
$t->thispage = "cscap-usage";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Sustainable Corn Data Usage Agreement</h3>

<p>By using these data, you acknowledge and agree to cite the data in all 
publications or presentations using the following format:</p>

<p>Abendroth, Lori J., Daryl E. Herzmann, Giorgi Chighladze, Eileen J. Kladivko, Matthew J. Helmers, Laura Bowling, Michael Castellano, 
Richard M. Cruse, Warren A. Dick, Norman R. Fausey, Jane Frankenberger, Aaron J. Gassmann, Alexandra Kravchenko, Rattan Lal, 
Joseph G. Lauer, Daren S. Mueller, Emerson D. Nafziger, Nsalambi Nkongolo, Matthew O'Neal, John E. Sawyer, Peter Scharf, 
Jeffrey S. Strock, and Maria B. Villamil. 2017. Sustainable Corn CAP (USDA-NIFA Funded). National Agricultural Library - ARS - USDA. 
<a>https://dx.doi.org/xxxxxxx</a>
</p>

<p>You are encouraged to contact the Sustainable Corn CAP personnel listed above to ensure proper data interpretation and may also 
consider co-authoring with them. You shall have no claim of ownership to any intellectual property rights in any part of the data, 
content, functions, features, code, data exploration tools, logos or other intellectual property comprising this database.
</p>

<p>The coauthors individually and the Sustainable Corn CAP collectively shall NOT be responsible or liable for the accuracy, reliability 
and completeness of any information included in the database as well as for the suitability of its application for any particular purpose. 
Data users are encouraged to notify the coauthors regarding data quality and other issues concerning the data, tools, and functionality of 
this website. Contact <a href="mailto:sustainablecorn@iastate.edu">sustainablecorn@iastate.edu</a> with any questions or concerns regarding 
usage and application of the data available at this site.
</p>

EOF;
$t->render('single.phtml');

?>
