<?php 
require_once "../../../include/require_auth.php";

function build_treatments_ui(){
	$s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Continuous Corn</div>
  <div class="panel-body">

<input type="checkbox" value="ROT1" data-treatment="ROT1" name="treatments[]" id="ROT1">
<label for="ROT1" class="control-label">continuous corn</label>
<br /><input type="checkbox" value="ROT38" data-treatment="ROT38" name="treatments[]" id="ROT38">
<label for="ROT38" class="control-label">continuous corn with rye cover</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Continuous Soybean</div>
  <div class="panel-body">

<input type="checkbox" value="ROT2" data-treatment="ROT2" name="treatments[]" id="ROT2">
<label for="ROT2" class="control-label">continuous soybean</label>
<br /><input type="checkbox" value="ROT39" data-treatment="ROT39" name="treatments[]" id="ROT39">
<label for="ROT39" class="control-label">continuous soybean with rye cover</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Corn-Corn-Corn-Corn-Soybean</div>
  <div class="panel-body">

<input type="checkbox" value="_T5" data-treatment="_T5" name="treatments[]" id="_T5">
<label for="_T5" class="control-label">Corn-Corn-Corn-Corn-Soybean</label>

<br /><input type="checkbox" value="_T6" data-treatment="_T6" name="treatments[]" id="_T6">
<label for="_T6" class="control-label">Corn-Corn-Corn-Corn-Soybean  with rye</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Corn-Soybean</div>
  <div class="panel-body">

<input type="checkbox" value="_T1" data-treatment="_T1" name="treatments[]" id="_T1">
<label for="_T1" class="control-label">corn-soybean</label>

<br /><input type="checkbox" value="_T2" data-treatment="_T2" name="treatments[]" id="_T2">
<label for="_T2" class="control-label">corn-soybean-wheat</label>

<br /><input type="checkbox" value="_T3" data-treatment="_T3" name="treatments[]" id="_T3">
<label for="_T3" class="control-label">Corn-Soybean-Wheat/Red Clover or mixed cover crop</label>

<br /><input type="checkbox" value="_T4" data-treatment="_T4" name="treatments[]" id="_T4">
<label for="_T4" class="control-label">Corn-Soybean with rye cover</label>

<br /><input type="checkbox" value="ROT41" data-treatment="ROT41" name="treatments[]" id="ROT41">
<label for="ROT41" class="control-label">CORN-corn-soybean-corn-soybean</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Prairie</div>
  <div class="panel-body">

<input type="checkbox" value="_T7" data-treatment="_T7" name="treatments[]" id="_T7">
<label for="_T7" class="control-label">Prairie</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Drainage</div>
  <div class="panel-body">

<input type="checkbox" value="DWM3" data-treatment="DWM3" name="treatments[]" id="DWM3">
<label for="DWM3" class="control-label">Controlled drainage ("managed")</label>
<br /><input type="checkbox" value="DWM2" data-treatment="DWM2" name="treatments[]" id="DWM2">
<label for="DWM2" class="control-label">Conventional drainage ("free")</label>
<br /><input type="checkbox" value="DWM5" data-treatment="DWM5" name="treatments[]" id="DWM5">
<label for="DWM5" class="control-label">Drainage with subirrigation</label>
<br /><input type="checkbox" value="DWM1" data-treatment="DWM1" name="treatments[]" id="DWM1">
<label for="DWM1" class="control-label">No drainage</label>
<br /><input type="checkbox" value="DWM4" data-treatment="DWM4" name="treatments[]" id="DWM4">
<label for="DWM4" class="control-label">Shallow drainage</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Tillage</div>
  <div class="panel-body">

<input type="checkbox" value="TIL4" data-treatment="TIL4" name="treatments[]" id="TIL4">
<label for="TIL4" class="control-label">Conventional Tillage (2011), No Tillage (2012-2015)</label>
<br /><input type="checkbox" value="TIL2" data-treatment="TIL2" name="treatments[]" id="TIL2">
<label for="TIL2" class="control-label">Conventional Tillage (CT)</label>
<br /><input type="checkbox" value="TIL1" data-treatment="TIL1" name="treatments[]" id="TIL1">
<label for="TIL1" class="control-label">No Tillage (NT)</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Nitrogen</div>
  <div class="panel-body">

<input type="checkbox" value="NIT2" data-treatment="NIT2" name="treatments[]" id="NIT2">
<label for="NIT2" class="control-label">MRTN application of N fertilizer</label>
<br /><input type="checkbox" value="NIT1" data-treatment="NIT1" name="treatments[]" id="NIT1">
<label for="NIT1" class="control-label">No nitrogen fertilizer applied</label>
<br /><input type="checkbox" value="NIT3" data-treatment="NIT3" name="treatments[]" id="NIT3">
<label for="NIT3" class="control-label">Sensor based N application (mid-season) - MO/OH rec</label>
<br /><input type="checkbox" value="NIT4" data-treatment="NIT4" name="treatments[]" id="NIT4">
<label for="NIT4" class="control-label">Sensor based N application (mid-season) - OK rec</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Landscape</div>
  <div class="panel-body">

<input type="checkbox" value="LND1" data-treatment="LND1" name="treatments[]" id="LND1">
<label for="LDN1" class="control-label">Near-summit</label>
<br /><input type="checkbox" value="LND2" data-treatment="LND2" name="treatments[]" id="LND2">
<label for="LDN2" class="control-label">Side slope</label>
<br /><input type="checkbox" value="LND3" data-treatment="LND3" name="treatments[]" id="LND3">
<label for="LND3" class="control-label">Toe slope</label>

  </div>
</div>


</div></div>
EOF;
	return $s;
}

function build_agronomic_ui(){
	$s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Corn</div>
  <div class="panel-body">

	<input type="checkbox" value="AGR32" data-agronomic="AGR32" name="agronomic[]" id="AGR32">
<label for="AGR32" class="control-label">Corn cob biomass at R6 (dry)</label>
	<br /><input type="checkbox" value="AGR24" data-agronomic="AGR24" name="agronomic[]" id="AGR24">
<label for="AGR24" class="control-label">Corn cob total carbon at R6</label>
	<br /><input type="checkbox" value="AGR26" data-agronomic="AGR26" name="agronomic[]" id="AGR26">
<label for="AGR26" class="control-label">Corn cob total nitrogen at R6</label>
	<br /><input type="checkbox" value="AGR1" data-agronomic="AGR1" name="agronomic[]" id="AGR1">
<label for="AGR1" class="control-label">Corn final plant population</label>
	<br /><input type="checkbox" value="AGR33" data-agronomic="AGR33" name="agronomic[]" id="AGR33">
<label for="AGR33" class="control-label">Corn grain biomass at R6 (dry)</label>
	<br /><input type="checkbox" value="AGR18" data-agronomic="AGR18" name="agronomic[]" id="AGR18">
<label for="AGR18" class="control-label">Corn grain moisture</label>
	<br /><input type="checkbox" value="AGR23" data-agronomic="AGR23" name="agronomic[]" id="AGR23">
<label for="AGR23" class="control-label">Corn grain total carbon at R6</label>
	<br /><input type="checkbox" value="AGR25" data-agronomic="AGR25" name="agronomic[]" id="AGR25">
<label for="AGR25" class="control-label">Corn grain total nitrogen at R6</label>
	<br /><input type="checkbox" value="AGR17" data-agronomic="AGR17" name="agronomic[]" id="AGR17">
<label for="AGR17" class="control-label">Corn grain yield at 15.5% MB</label>
	<br /><input type="checkbox" value="AGR4" data-agronomic="AGR4" name="agronomic[]" id="AGR4">
<label for="AGR4" class="control-label">Corn vegetative biomass at R6 (dry)</label>
	<br /><input type="checkbox" value="AGR9" data-agronomic="AGR9" name="agronomic[]" id="AGR9">
<label for="AGR9" class="control-label">Corn vegetative biomass total carbon at R6</label>
	<br /><input type="checkbox" value="AGR10" data-agronomic="AGR10" name="agronomic[]" id="AGR10">
<label for="AGR10" class="control-label">Corn vegetative biomass total nitrogen at R6</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Cover Crop</div>
  <div class="panel-body">

	<input type="checkbox" value="AGR39" data-agronomic="AGR39" name="agronomic[]" id="AGR39">
<label for="AGR39" class="control-label">Cover crop (rye) and weedy biomass at termination (spring)</label>
	<br /><input type="checkbox" value="AGR7" data-agronomic="AGR7" name="agronomic[]" id="AGR7">
<label for="AGR7" class="control-label">Cover crop (rye) biomass at termination (spring) (no significant weeds)</label>
	<br /><input type="checkbox" value="AGR6" data-agronomic="AGR6" name="agronomic[]" id="AGR6">
<label for="AGR6" class="control-label">Cover crop (rye) biomass in late fall (no significant weeds)</label>
	<br /><input type="checkbox" value="AGR3" data-agronomic="AGR3" name="agronomic[]" id="AGR3">
<label for="AGR3" class="control-label">Mid-season canopy N sensing</label>
	<br /><input type="checkbox" value="AGR41" data-agronomic="AGR41" name="agronomic[]" id="AGR41">
<label for="AGR41" class="control-label">Red clover or mixed cover crop biomass in late fall of previous year</label>
	<br /><input type="checkbox" value="AGR43" data-agronomic="AGR43" name="agronomic[]" id="AGR43">
<label for="AGR43" class="control-label">Red clover or mixed cover crop total carbon in late fall of previous year</label>
	<br /><input type="checkbox" value="AGR46" data-agronomic="AGR46" name="agronomic[]" id="AGR46">
<label for="AGR46" class="control-label">Red clover or mixed cover crop total carbon in spring of spreadsheet year</label>
	<br /><input type="checkbox" value="AGR42" data-agronomic="AGR42" name="agronomic[]" id="AGR42">
<label for="AGR42" class="control-label">Red clover or mixed cover crop total nitrogen in late fall of previous year</label>
	<br /><input type="checkbox" value="AGR13" data-agronomic="AGR13" name="agronomic[]" id="AGR13">
<label for="AGR13" class="control-label">Rye biomass total carbon at fall</label>
	<br /><input type="checkbox" value="AGR15" data-agronomic="AGR15" name="agronomic[]" id="AGR15">
<label for="AGR15" class="control-label">Rye biomass total carbon at spring</label>
	<br /><input type="checkbox" value="AGR14" data-agronomic="AGR14" name="agronomic[]" id="AGR14">
<label for="AGR14" class="control-label">Rye biomass total nitrogen at fall</label>
	<br /><input type="checkbox" value="AGR16" data-agronomic="AGR16" name="agronomic[]" id="AGR16">
<label for="AGR6" class="control-label">Rye biomass total nitrogen at spring</label>
	<br /><input type="checkbox" value="AGR40" data-agronomic="AGR40" name="agronomic[]" id="AGR40">
<label for="AGR40" class="control-label">Weedy biomass (only) at termination (spring)</label>


  </div>
</div>


</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soybean</div>
  <div class="panel-body">

	<input type="checkbox" value="AGR2" data-agronomic="AGR2" name="agronomic[]" id="AGR2">
<label for="AGR2" class="control-label">Soybean final plant population</label>
	<br /><input type="checkbox" value="AGR34" data-agronomic="AGR34" name="agronomic[]" id="AGR34">
<label for="AGR34" class="control-label">Soybean grain biomass at R8 (dry)</label>
	<br /><input type="checkbox" value="AGR20" data-agronomic="AGR20" name="agronomic[]" id="AGR20">
<label for="AGR20" class="control-label">Soybean grain moisture</label>
	<br /><input type="checkbox" value="AGR27" data-agronomic="AGR27" name="agronomic[]" id="AGR27">
<label for="AGR27" class="control-label">Soybean grain total carbon at R8</label>
	<br /><input type="checkbox" value="AGR28" data-agronomic="AGR28" name="agronomic[]" id="AGR28">
<label for="AGR28" class="control-label">Soybean grain total nitrogen at R8</label>
	<br /><input type="checkbox" value="AGR19" data-agronomic="AGR19" name="agronomic[]" id="AGR19">
<label for="AGR19" class="control-label">Soybean grain yield at 13.0% MB</label>
	<br /><input type="checkbox" value="AGR5" data-agronomic="AGR5" name="agronomic[]" id="AGR5">
<label for="AGR5" class="control-label">Soybean vegetative biomass at R8 (stems and pods only; no leaves)</label>
	<br /><input type="checkbox" value="AGR11" data-agronomic="AGR11" name="agronomic[]" id="AGR11">
<label for="AGR11" class="control-label">Soybean vegetative biomass total carbon at R8</label>
	<br /><input type="checkbox" value="AGR12" data-agronomic="AGR12" name="agronomic[]" id="AGR12">
<label for="AGR12" class="control-label">Soybean vegetative biomass total nitrogen at R8</label>


  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Wheat</div>
  <div class="panel-body">

	<input type="checkbox" value="AGR22" data-agronomic="AGR22" name="agronomic[]" id="AGR22">
<label for="AGR22" class="control-label">Wheat grain moisture</label>
	<br /><input type="checkbox" value="AGR21" data-agronomic="AGR21" name="agronomic[]" id="AGR21">
<label for="AGR21" class="control-label">Wheat grain yield at 13.5% MB</label>

  </div>
</div>



</div></div>
EOF;
	return $s;
}

function build_soil_ui(){
	$s = <<<EOF
<div class="row"><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Water Retention</div>
  <div class="panel-body">

	<input type="checkbox" value="_S1" data-soil="_S1" name="soil[]" id="_S1">
<label for="_S1" class="control-label">Water retention</label>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Soil Nitrogen</div>
  <div class="panel-body">

	<input type="checkbox" value="SOIL22" data-soil="SOIL22" name="soil[]" id="SOIL22">
<label for="SOIL22" class="control-label">Soil Ammonium</label>
	<br /><input type="checkbox" value="SOIL15" data-soil="SOIL15" name="soil[]" id="SOIL15">
<label for="SOIL15" class="control-label">Soil Nitrate</label>
	<br /><input type="checkbox" value="SOIL14" data-soil="SOIL14" name="soil[]" id="SOIL14">
<label for="SOIL14" class="control-label">Total N</label>

  </div>
</div>

</div><div class="col-md-4">

<div class="panel panel-default">
  <div class="panel-heading">Soil Properties</div>
  <div class="panel-body">

	<input type="checkbox" value="SOIL7" data-soil="SOIL7" name="soil[]" id="SOIL7">
<label for="SOIL7" class="control-label">Aggregate stability</label>
	<br /><input type="checkbox" value="SOIL12" data-soil="SOIL12" name="soil[]" id="SOIL12">
<label for="SOIL12" class="control-label">Cation Exchange Capacity (CEC)</label>
	<br /><input type="checkbox" value="SOIL1" data-soil="SOIL1" name="soil[]" id="SOIL1">
<label for="SOIL1" class="control-label">Dry bulk density (BD)</label>
	<br /><input type="checkbox" value="SOIL3" data-soil="SOIL3" name="soil[]" id="SOIL3">
<label for="SOIL3" class="control-label">Infiltration rate</label>
	<br /><input type="checkbox" value="SOIL11" data-soil="SOIL11" name="soil[]" id="SOIL11">
<label for="SOIL11" class="control-label">Soil pH</label>
	<br /><input type="checkbox" value="SOIL6" data-soil="SOIL6" name="soil[]" id="SOIL6">
<label for="SOIL6" class="control-label">Soil texture</label>

  </div>
</div>

</div><div class="col-md-4">


<div class="panel panel-default">
  <div class="panel-heading">Soil Components</div>
  <div class="panel-body">

	<br /><input type="checkbox" value="SOIL28" data-soil="SOIL28" name="soil[]" id="SOIL28">
<label for="SOIL28" class="control-label">Percent Clay</label>
	<br /><input type="checkbox" value="SOIL26" data-soil="SOIL26" name="soil[]" id="SOIL26">
<label for="SOIL26" class="control-label">Percent Sand</label>
	<br /><input type="checkbox" value="SOIL27" data-soil="SOIL27" name="soil[]" id="SOIL27">
<label for="SOIL27" class="control-label">Percent Silt</label>


  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Soil Carbon</div>
  <div class="panel-body">

	<br /><input type="checkbox" value="SOIL13" data-soil="SOIL13" name="soil[]" id="SOIL13">
<label for="SOIL13" class="control-label">Soil Organic Carbon (SOC)</label>

  </div>
</div>



</div></div>
EOF;
	return $s;
}

function build_theses(){
	$pgconn = pg_connect("dbname=sustainablecorn host=iemdb user=nobody");
	$rs = pg_query($pgconn, "select * from theses ".
			"ORDER by authors");
	$s = "\n";
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
		$s .= sprintf("<p>%s %s %s %s <a href=\"%s\">%s</a></p>\n",
				$row['authors'], $row["year"], $row['title'],
				$row["journal_or_source"],
				$row["online_source"], $row["online_source"]);
	}
	$s .= "\n";
	return $s;
}

function build_publications(){
	$pgconn = pg_connect("dbname=sustainablecorn host=iemdb user=nobody");
	$rs = pg_query($pgconn, "select * from refereed_journals ".
			"ORDER by authors");
	$s = "\n";
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
		$strong =  ($row["open_access"] == 'Yes') ? "<strong>" : '';
		$endstrong =  ($row["open_access"] == 'Yes')? "</strong>": '';
		$s .= sprintf("<p>%s%s %s %s %s %s %s <a href=\"%s\">%s</a>%s</p>\n",
				$strong,
				$row['authors'], $row["year"], $row['title'],
				$row["journal_or_source"], $row["vol"], $row["pg_no."],
				$row["online_source"], $row["online_source"], $endstrong);
	}
	$s .= "\n";
	return $s;
}

function build_sites_ui(){
	$states = Array("IA" => "Iowa",
		"MN" => "Minnesota",
		"WI" => "Wisconsin",
		"IL" => "Illinois",
		"MO" => "Missouri",
		"IN" => "Indiana",
		"MI" => "Michigan",
		"OH" => "Ohio");
	$pgconn = pg_connect("dbname=mesosite host=iemdb user=nobody");
	$rs = pg_query($pgconn, "SELECT * from stations where network = 'CSCAP'".
			" and id !~* 'ONFARM' and ".
			"id not in ('VICMS', 'NAEW.Y102', 'NAEW.Y103', 'NAEW.WS115', ".
			" 'NAEW.WS123', 'NAEW.WS127') ORDER by name ASC");
	$data = Array();
	for ($i=0; $row=@pg_fetch_assoc($rs, $i); $i++){
		$data[$row["state"]][$row["id"]] = $row["name"];
	}
	$keys = array_keys($data);
	asort($keys);
	$s = '';
	$q = -1;	
	while (list($v,$k)=each($keys)){
		$q += 1;
		if ($q % 3 == 0){
			$s .= "<div class=\"col-md-4\">\n";
		}
		$s .= sprintf("<div class=\"panel panel-default\">".
  "<div class=\"panel-heading\">".
  "<input type=\"checkbox\" class=\"state-check\" value=\"%s\">%s</div>".
  "<div class=\"panel-body\">\n", $k, $states[$k]);
		while (list($v2, $k2)=each($data[$k])){
			$s .= sprintf("<input type=\"checkbox\" value=\"%s\"".
					" data-state=\"%s\" name=\"sites[]\" class=\"site-check\"".
					">%s</br >\n", $v2, $k, $k2);
		}
		$s .= "</div></div>\n";
		if ($q % 3 == 2){
			$s .= "</div>\n";
		}
	}
	if ($q % 3 != 2){
		$s .= "</div>\n";
	}
	return $s;
}

function build_year_ui(){
	$years = Array(2011, 2012, 2013, 2014, 2015);
	$s = '';
	while (list($k, $v)=@each($years)){
		$s .= sprintf("<br /><input type=\"checkbox\" value=\"%s\"".
				" data-year=\"%s\" name=\"year[]\" id=\"Y%s\">".
				"<label for=\"Y%s\" class=\"control-label\">%s</label>\n",
				$v, $v, $v, $v, $v);
	}
	return $s;
}

function build_ghg_ui(){
	$s = <<<EOF
	<div class="panel panel-default">
	<div class="panel-heading">Available Variables</div>
	<div class="panel-body">
	
	<input type="checkbox" value="GHG01" data-ghg="GHG01" name="ghg[]" id="GHG01">
	<label for="GHG01" class="control-label">Method</label>
	<br /><input type="checkbox" value="GHG02" data-ghg="GHG02" name="ghg[]" id="GHG02">
	<label for="GHG02" class="control-label">Chamber Position</label>
	<br /><input type="checkbox" value="GHG03" data-ghg="GHG03" name="ghg[]" id="GHG03">
	<label for="GHG03" class="control-label">Carbon Dioxide (CO2-C) flux</label>
	<br /><input type="checkbox" value="GHG04" data-ghg="GHG04" name="ghg[]" id="GHG04">
	<label for="GHG04" class="control-label">Carbon Dioxide (CO2) correlation coefficient (R2)</label>
	<br /><input type="checkbox" value="GHG05" data-ghg="GHG05" name="ghg[]" id="GHG05">
	<label for="GHG05" class="control-label">Nitrous Oxide (N2O-N) flux</label>
	<br /><input type="checkbox" value="GHG06" data-ghg="GHG06" name="ghg[]" id="GHG06">
	<label for="GHG06" class="control-label">Nitrous Oxide (N2O) correlation coefficient (R2)</label>
	<br /><input type="checkbox" value="GHG07" data-ghg="GHG07" name="ghg[]" id="GHG07">
	<label for="GHG07" class="control-label">Ammonia (NH3-N) flux</label>
	<br /><input type="checkbox" value="GHG08" data-ghg="GHG08" name="ghg[]" id="GHG08">
	<label for="GHG08" class="control-label">Ammonia (NH3) correlation coefficient (R2)</label>
	<br /><input type="checkbox" value="GHG09" data-ghg="GHG09" name="ghg[]" id="GHG09">
	<label for="GHG09" class="control-label">Methane (CH4-C) flux</label>
	<br /><input type="checkbox" value="GHG10" data-ghg="GHG10" name="ghg[]" id="GHG10">
	<label for="GHG10" class="control-label">Methane (CH4) correlation coefficient (R2)</label>
	<br /><input type="checkbox" value="GHG11" data-ghg="GHG11" name="ghg[]" id="GHG11">
	<label for="GHG11" class="control-label">Ammonium (NH4) flux</label>
	<br /><input type="checkbox" value="GHG12" data-ghg="GHG12" name="ghg[]" id="GHG12">
	<label for="GHG12" class="control-label">Ammonium (NH4) correlation coefficient (R2)</label>
	<br /><input type="checkbox" value="GHG13" data-ghg="GHG13" name="ghg[]" id="GHG13">
	<label for="GHG13" class="control-label">Volumetric soil moisture at 5 cm</label>
	<br /><input type="checkbox" value="GHG14" data-ghg="GHG14" name="ghg[]" id="GHG14">
	<label for="GHG14" class="control-label">Soil Temperature at 5 cm</label>
	<br /><input type="checkbox" value="GHG15" data-ghg="GHG15" name="ghg[]" id="GHG15">
	<label for="GHG15" class="control-label">Soil Nitrate (NO3-N) at 0-10 cm</label>
	<br /><input type="checkbox" value="GHG16" data-ghg="GHG16" name="ghg[]" id="GHG16">
	<label for="GHG16" class="control-label">Soil Ammonium (NH4-N) at 0-10 cm</label>
	
	</div>
	</div>
EOF;
	return $s;
}

function build_ipm_ui(){
	$s = <<<EOF
	<div class="panel panel-default">
	<div class="panel-heading">Available Variables</div>
	<div class="panel-body">

	<input type="checkbox" value="IPM01" data-ipm="IPM01" name="ipm[]" id="IPM01">
	<label for="IPM01" class="control-label">Insect Sampling Methods</label>
	<br /><input type="checkbox" value="IPM02" data-ipm="IPM02" name="ipm[]" id="IPM02">
	<label for="IPM02" class="control-label">Insect Common Name</label>
	<br /><input type="checkbox" value="IPM03" data-ipm="IPM03" name="ipm[]" id="IPM03">
	<label for="IPM03" class="control-label">Insect Class</label>
	<br /><input type="checkbox" value="IPM04" data-ipm="IPM04" name="ipm[]" id="IPM04">
	<label for="IPM04" class="control-label">Insect Order</label>
	<br /><input type="checkbox" value="IPM05" data-ipm="IPM05" name="ipm[]" id="IPM05">
	<label for="IPM05" class="control-label">Insect Family</label>
	<br /><input type="checkbox" value="IPM06" data-ipm="IPM06" name="ipm[]" id="IPM06">
	<label for="IPM06" class="control-label">Insect Species</label>
	<br /><input type="checkbox" value="IPM07" data-ipm="IPM07" name="ipm[]" id="IPM07">
	<label for="IPM07" class="control-label">Insect Population</label>
	<br /><input type="checkbox" value="IPM08" data-ipm="IPM08" name="ipm[]" id="IPM08">
	<label for="IPM08" class="control-label">Insect population measurement unit</label>
	<br /><input type="checkbox" value="IPM09" data-ipm="IPM09" name="ipm[]" id="IPM09">
	<label for="IPM09" class="control-label">Plant Sample Number</label>
	<br /><input type="checkbox" value="IPM10" data-ipm="IPM10" name="ipm[]" id="IPM10">
	<label for="IPM10" class="control-label">Plant sampled</label>
	<br /><input type="checkbox" value="IPM11" data-ipm="IPM11" name="ipm[]" id="IPM11">
	<label for="IPM11" class="control-label">Plant component assessed for damage</label>
	<br /><input type="checkbox" value="IPM12" data-ipm="IPM12" name="ipm[]" id="IPM12">
	<label for="IPM12" class="control-label">Disease/Damage type</label>
	<br /><input type="checkbox" value="IPM13" data-ipm="IPM13" name="ipm[]" id="IPM13">
	<label for="IPM13" class="control-label">Position assessed</label>
	<br /><input type="checkbox" value="IPM14" data-ipm="IPM14" name="ipm[]" id="IPM14">
	<label for="IPM14" class="control-label">Visual rating of damage due to disease or insect</label>
			
	</div>
	</div>
EOF;
	return $s;
}

function build_shm_ui(){
	$s = <<<EOF
	<div class="panel panel-default">
	<div class="panel-heading">Available Variables</div>
	<div class="panel-body">
			
	<input type="checkbox" value="SHM5" data-ipm="SHM5" name="shm[]" id="SHM5" checked="checked">
	<label for="SHM5" class="control-label">Data Dictionary</label>
	<br /><input type="checkbox" value="SHM4" data-ipm="SHM4" name="shm[]" id="SHM4" checked="checked">
	<label for="SHM4" class="control-label">Drainage Control Structure Management</label>
	<br /><input type="checkbox" value="SHM1" data-ipm="SHM1" name="shm[]" id="SHM1" checked="checked">
	<label for="SHM1" class="control-label">Field Operations</label>
	<br /><input type="checkbox" value="SHM2" data-ipm="SHM2" name="shm[]" id="SHM2" checked="checked">
	<label for="SHM2" class="control-label">Pesticides</label>
	<br /><input type="checkbox" value="SHM4" data-ipm="SHM4" name="shm[]" id="SHM4" checked="checked">
	<label for="SHM4" class="control-label">Plot Identifiers</label>
	<br /><input type="checkbox" value="SHM3" data-ipm="SHM3" name="shm[]" id="SHM3" checked="checked">
	<label for="SHM3" class="control-label">Residue, Irrigation</label>
			
	</div>
	</div>
EOF;
	return $s;
}

require_once "../../../include/myview.php";
$t = new MyView();
$t->title = "CSCAP Project Data Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
<style>
input[type=checkbox][disabled] + label {
    color: #ccc;
}
</style>
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="dl.js?v=3"></script>
EOF;

$sitesui = build_sites_ui();
$treatmentui = build_treatments_ui();
$agronomicui = build_agronomic_ui();
$soilui = build_soil_ui();
$yearui = build_year_ui();
$shmui = build_shm_ui();
$publisting = build_publications();
$theseslisting = build_theses();
$ghgui = build_ghg_ui();
$waterui = "";
$ipmui = build_ipm_ui();

$t->content = <<<EOF


 <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#data" aria-controls="data" role="tab" data-toggle="tab">Data</a></li>
    <li role="presentation"><a href="#pubs" aria-controls="pubs" role="tab" data-toggle="tab">Refereed Journals</a></li>
    <li role="presentation"><a href="#sites" aria-controls="sites" role="tab" data-toggle="tab">Research Sites</a></li>
    <li role="presentation"><a href="#theses" aria-controls="theses" role="tab" data-toggle="tab">Theses and Dissertations</a></li>
  </ul>
  
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="data">

<h2>CSCAP Data Download</h2>
    
<form method="POST" action="dl.py">
<div class="btn-group fauxtabs" role="group" aria-label="Pages">
  <button type="button" class="btn btn-primary" id="sites-btn">Sites</button>
  <button type="button" class="btn btn-default" id="treatments-btn">Treatments</button>
  <button type="button" class="btn btn-default" id="agronomic-btn">Agronomic</button>
  <button type="button" class="btn btn-default" id="soil-btn">Soil</button>
  <button type="button" class="btn btn-default" id="ghg-btn">GHG</button>
  <button type="button" class="btn btn-default" id="water-btn">Water</button>
  <button type="button" class="btn btn-default" id="ipm-btn">IPM</button>
  <button type="button" class="btn btn-default" id="year-btn">Year</button>
  <button type="button" class="btn btn-default" id="shm-btn">Site History, Management</button>
  <button type="button" class="btn btn-default" id="option-btn">Export Options</button>
</div>

<div id="sites-ui" style="display: block;">
<div class="pull-right">
<button id="sites-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
<h3>Available Research Sites</h3>
{$sitesui}
</div>
<div id="treatments-ui" style="display: none;">
<div class="pull-right">
  <button id="treatments-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Treatments</h3>
{$treatmentui}
</div>
<div id="agronomic-ui" style="display: none;">
<div class="pull-right">
  <button id="agronomic-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Agronomic</h3>
{$agronomicui}
</div>
<div id="soil-ui" style="display: none;">
<div class="pull-right">
  <button id="soil-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Soil</h3>
{$soilui}
</div>
<div id="ghg-ui" style="display: none;">
<div class="pull-right">
  <button id="ghg-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Green House Gases (GHG)</h3>
{$ghgui}
</div>
<div id="water-ui" style="display: none;">
<div class="pull-right">
  <button id="water-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Water</h3>
{$waterui}
</div>
<div id="ipm-ui" style="display: none;">
<div class="pull-right">
  <button id="ipm-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>
	<h3>Integrated Pest Management (IPM)</h3>
{$ipmui}
</div>
<div id="year-ui" style="display: none;">
<div class="pull-right">
  <button id="year-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>

	<h3>Available Crop Years with Data</h3>
{$yearui}
</div>

<div id="shm-ui" style="display: none;">
<div class="pull-right">
  <button id="shm-selectall" type="button" class="btn btn-default sa"><i class="glyphicon glyphicon-ok"></i> Select All</button>
</div>

{$shmui}
</div>

<div id="option-ui" style="display: none;">
	<h3>Available Export Options</h3>

<p>How to handle values below detection limit:
<select name="detectlimit">
	<option value="1">Keep them as is, presented as "&lt; LOD"</option>
	<option value="2">Divide the LOD value by two</option>
	<option value="3">Divide the LOD value by square root of two</option>
	<option value="4">Omit all occurrences and replace as missing</option>
</select></p>

<p>How to represent missing values:
<select name="missing">
	<option value="M">M</option>
	<option value="N/A">N/A</option>
	<option value="NaN">NaN</option>
	<option value="NULL">NULL</option>
	<option value=" ">((blank space))</option>
	<option value=".">.</option>
</select></p>

<p><input type="submit" value="Proceed with Download"></p>

		
</div>
<br clear="both" />
<div class="pull-right">
<button id="prev-btn" type="button" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> Previous</button>
<button id="next-btn" type="button" class="btn btn-default">Next <i class="glyphicon glyphicon-arrow-right"></i></button>
</div>
</form>
		</div>
		<div role="tabpanel" class="tab-pane" id="pubs">
<h3>CSCAP Team Publications</h3>

<p><blockquote>Articles with open access availability are <strong>in bold</strong>.
These do not require a subscription to the journal to access.</blockquote></p>

{$publisting}
		</div>
		<div role="tabpanel" class="tab-pane" id="theses">
{$theseslisting}
		</div>
		<div role="tabpanel" class="tab-pane" id="sites">
<iframe src="https://www.google.com/maps/d/embed?mid=1VQuDqTRkO5RPvIgWMODYvBLWU1A" width="640" height="480"></iframe>
		</div>
		</div>
		
EOF;
$t->render('single.phtml');

?>