<?php 
// require_once "../../include/require_auth.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "Transforming Drainage Data and Tools";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Transforming Drainage Project Team Research Data</h3>

<div class="row">
<div class="col-md-6">
<div class="jumbotron">
  <h2>Visualization and Plotting Tools</h2>
  <p>Interactive tools that provide plots and downloadable datasets.</p>
  <p><a class="btn btn-primary btn-lg" href="/td/dl/#tab_wdata" role="button">View Tools</a></p>
</div>
</div>
<div class="col-md-6">
<div class="jumbotron">
  <h2>Research Data from Experimental Sites</h2>
  <p>Download the data you need.</p>
  <p><a class="btn btn-primary btn-lg" href="/td/dl/#tab_sites" role="button">View Download</a></p>
</div>
</div>
</div>


<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/tdbanner.png" class="img img-responsive" alt="TD Banner">
<div class="clearfix"></div>

EOF;
$t->render('single.phtml');
?>
