<?php 
// require_once "../../include/require_auth.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "TD Data Portal";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Future Site for Transforming Drainage Project Team Research Data</h3>

<p><img src="/images/tdteam.jpg" class="img img-responsive" alt="TD Team" align="middle" width="35%" height="35%"></p>

<p>This website will contain research data measured across a set of experiments 
carried out by the “Managing Water for Increased Resiliency of Drained Agricultural 
Landscapes” project or <a href="https://transformingdrainage.org/" target="_blank">Transforming Drainage</a>. 
This project is funded from 2015-2020 by the United States Department of Agriculture, 
National Institute of Food and Agriculture (USDA-NIFA, Award No. 2015-68007-23193). 
Data will be publicly available after the project is completed.</p>

<p>The team is a multi-state research, extension, and education effort aimed at addressing 
  important drainage management questions through the assessment and development of new 
  water storage practices and technologies. Drainage is an essential component of the 
  landscape to provide suitable growing conditions for the crops that feed and support 
  both local and global communities. However, this infrastructure also creates a pathway 
  for water and nutrient losses to occur. Increasing water storage on the landscape can 
  provide greater water security for growing crops while supporting water quality efforts, 
  which are of growing interest to landowners and the public. The vision for this project 
  is that the process of designing and implementing agricultural drainage will be transformed 
  so that storing water in the landscape will be considered for every drainage system as a 
  foundation for resilient and productive agricultural systems.</p>

<p>Research data have been and are collected across 42 experimental sites focused on control 
  drainage, water recycling, or saturated buffers, beginning in 1996. At the end of the project 
  award period, the team will make all water quality and quantity data available here.</p>

<p>For questions on the project, please contact the project director, 
  <a href="mailto:frankenb@purdue.edu">Jane Frankenberger</a>, and the project manager, 
  <a href="mailto:breinhar@purdue.edu">Ben Reinhart</a>. For questions on the research database, 
  please contact Lori Abendroth and Giorgi Chighladze at <a href="mailto:isudatateam@iastate.edu">isudatateam@iastate.edu</a>.</p>
 

<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/tdbanner.png" class="img img-responsive" alt="TD Banner">
<div class="clearfix"></div>

EOF;
$t->render('single.phtml');
?>
