<?php 
// require_once "../../include/require_auth.php";
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "TD Data Portal";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Transforming Drainage Project Team Research Data</h3>

<p><img src="/images/tdteam.jpg" class="img img-responsive" alt="TD Team" width="50%"></p>

<p>This website contains research data measured across a set of experiments 
carried out by the “Managing Water for Increased Resiliency of Drained 
Agricultural Landscapes” project or Transforming Drainage. This project 
is funded from 2015-2020 by the United States Department of Agriculture, 
National Institute of Food and Agriculture (USDA-NIFA, 
Award No. 2015-68007-23193).</p>

<p>The Transforming Drainage Project worked to advance the process of 
designing and implementing agricultural drainage systems for storing water in 
the landscape to improve the resiliency and productivity of agricultural 
systems. Drainage is an essential component of the landscape to provide 
suitable growing conditions for the crops that feed and support both local 
and global communities. Increasing water storage on the landscape can 
provide greater water security for crop production while reducing the loss 
of water and nutrients through this infrastructure.</p>

<p>Research data were collected across 39 experimental sites focused on 
controlled drainage, drainage water recycling, and saturated buffers, 
beginning in 1996.</p>

<p>The Transforming Drainage Project's annual reports, proposals, 
technical reports, and publications are available at the Iowa 
State/Purude University Digital Repository (website TBD). 
The Transforming Drainage Project research data are also stored 
at the USDA National Agricultural Library Ag Data Commons (website TBD).</p>

<p>Project Director: Jane Frankenberger</p>
<p>Project Manager: Ben Reinhart</p>
<p>Research Data and Visualization Tools: Lori Abendroth, Giorgi Chighladze,
Daryl Herzmann (<a href="mailto:isudatateam@iastate.edu">isudatateam@iastate.edu</a>)</p>

  <p>&nbsp;</p>
  <div class="clearfix"></div>
  <div class="pull-right">
  <a class="btn btn-primary" href="data.phtml"><i class="fa fa-arrow-right"></i> View Tools &amp; Data</a>
  </div>
  
<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/tdbanner.png" class="img img-responsive" alt="TD Banner">
<div class="clearfix"></div>

EOF;
$t->render('single.phtml');
?>
