<?php 
require_once "../../include/myview.php";
$t = new MyView();
$t->title = "TD Data Portal";
$t->content = <<<EOF
<p>&nbsp;</p>

<h3>Transforming Drainage Project Team Research Data (drainagedata.org)</h3>

<p><img src="/images/tdhomepage.gif" class="img img-responsive" alt="TD Team"></p>

<p>This website contains research data measured across a set of experiments
carried out by the “Managing Water for Increased Resiliency of Drained
Agricultural Landscapes” project or
<a href="https://transformingdrainage.org/" target="_blank">Transforming Drainage</a>.
This project is funded from 2015-2020 by the United States Department of
Agriculture, National Institute of Food and Agriculture (USDA-NIFA, Award No.
2015-68007-23193).</p>

<p>The Transforming Drainage Project worked to advance the process of designing
and implementing agricultural drainage systems for storing water in the landscape
to improve the resiliency and productivity of agricultural systems. Drainage
is an essential component of the landscape to provide suitable growing conditions
for the crops that feed and support both local and global communities. Increasing
water storage on the landscape can provide greater water security for crop
production while reducing the loss of water and nutrients through this
infrastructure.</p>

<p>These data began in 1996 and include plot- and watershed-level measurements
for 39 experiments across the Midwest and North Carolina. Practices studied
include controlled drainage, drainage water recycling, and saturated buffers.
In total, 221 variables are reported and span 206 site-years for tile drainage,
153 for nitrate-N load, 180 for water quality, 91 for water table, and 196
for crop yield. The Transforming Drainage Project research data are also
stored at the USDA National Agricultural Library Ag Data Commons
(<a href="https://doi.org/10.15482/USDA.ADC/1521092" target="_blank">doi:10.15482/USDA.ADC/1521092</a>) repository.</p>

<p>Project Director: <a href="https://transformingdrainage.org/about-us/contact/" target="_blank">Jane Frankenberger</a></p>
<p>Project Manager: <a href="https://transformingdrainage.org/about-us/contact/" target="_blank">Ben Reinhart</a></p>
<p>Research Data and Visualization Tools: Lori Abendroth, Giorgi Chighladze,
Daryl Herzmann (<a href="mailto:isudatateam@iastate.edu">isudatateam@iastate.edu</a>)</p>

  <p>&nbsp;</p>
  <div class="clearfix"></div>
  <div class="pull-right">
  <a class="btn btn-primary" href="/td/dl/#tab_sites"><i class="fa fa-arrow-right"></i> View Tools &amp; Data</a>
  </div>
  
<div class="clearfix"></div>
<p>&nbsp;</p>
<img src="/images/tdbanner.png" class="img img-responsive" alt="TD Banner">
<div class="clearfix"></div>

EOF;
$t->render('single.phtml');
?>
