<?php
require_once "../../include/require_auth.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$HIGHCHARTS = "6.0.7";

$site = isset($_GET["site"]) ? $_GET["site"]: 'IA_Hamilton1';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';
$missing = isset($_GET["missing"]) ? $_GET["missing"]: "M";
$custom_missing = isset($_GET["custom_missing"]) ? $_GET["custom_missing"]: "";
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 100;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/*
 with data as (select siteid, min(date),
 max(date) from water_table_data GROUP by siteid)
 
 SELECT '"'||siteid ||'"=>"' || siteid || ' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "IA_Hamilton1"=>"IA_Hamilton1 (2011-01-01 to 2018-12-31) [2921 days]",
    "IA_Hamilton2"=>"IA_Hamilton2 (2016-07-11 to 2018-12-31) [903 days]",
    "IA_Hamilton3"=>"IA_Hamilton3 (2013-01-01 to 2018-11-02) [2131 days]",
    "IA_Washington"=>"IA_Washington (2007-07-16 to 2017-12-18) [3808 days]",
    "IN_Randolph"=>"IN_Randolph (2006-06-16 to 2017-10-25) [4149 days]",
    "IN_Tippecanoe"=>"IN_Tippecanoe (2017-07-17 to 2018-12-31) [532 days]",
    "MN_Clay1"=>"MN_Clay1 (2012-11-07 to 2018-04-30) [2000 days]",
    "MN_Clay2"=>"MN_Clay2 (2012-11-07 to 2018-12-31) [2245 days]",
    "MN_Clay3"=>"MN_Clay3 (2012-11-07 to 2018-10-31) [2184 days]",
    "MN_Redwood1"=>"MN_Redwood1 (2015-06-15 to 2016-10-24) [497 days]",
    "NC_Washington"=>"NC_Washington (2007-01-02 to 2012-12-31) [2190 days]",
    "ND_Richland"=>"ND_Richland (2014-04-30 to 2018-09-30) [1614 days]",
    "OH_Auglaize2"=>"OH_Auglaize2 (2011-01-13 to 2015-11-20) [1772 days]",
    "OH_Defiance2"=>"OH_Defiance2 (2000-03-09 to 2007-12-06) [2828 days]",
    "SD_Clay"=>"SD_Clay (2016-04-20 to 2016-11-04) [198 days]",   
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$ar = Array(
    "M" => "M",
    "N/A" => "N/A",
    "NaN" => "NaN",
    "NULL" => "NULL",
    " " => " ",
    "." => ".",
    "-999" => "-999",
    "__custom__" => "Custom Value",
);
$missselect = make_select('missing', $missing, $ar);

$jsextra = "";
if ($view != 'plot'){
    $imageurl = sprintf("plot_watertable.py?site=%s&date=%s&days=%s&ptype=%s". 
        "&view=%s&amp;group=%s&missing=%s&custom_missing=%s", 
		$site, $date, $days, $ptype, $view, $group, $missing, $custom_missing);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("watertable__%s__%s__%s__%s__%s.js", 
		$site, $date, $days, $ptype, $group);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

$t = new MyView();
$t->thispage = "td-watertable";
$t->title = "TD Water Table Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" /> 
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "watertable_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "depth_mm";
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2006, 0, 1),
        maxDate: new Date(2016, 1, 1)});
    $("select[name='missing']").change(function(){
        if ($(this).val() == '__custom__'){
            $("#missingvalue_opt").css('display', 'block');
        } else {
            $("#missingvalue_opt").css('display', 'none');
        }
    });	
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Water Table Data Plotting/Download</h3>

<p>Water Table Depth data included on this page are associated with the project:
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site:</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
<br /><input type="checkbox" name="group" value="1"${groupselected}> Average plot values by their drainage treatment
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Time-series Aggregation:</th><th>View and Download Options</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}
<br />
<div>
    <label for="missingvalue">How to represent missing values:</label>
{$missselect}
</div>

<div id="missingvalue_opt" style="display: none;">
    <label for="missingcustom">Enter Custom Missing Value:</label>
    <input value="{$custom_missing}" type="text" name="custom_missing" id="missingcustom">
</div>
</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>Plotting of data may not occur if the time period selected is more than 
~700 days. This is due to the amount of data overwhelming the user’s web 
browser and failing to load. Select a shorter time span if you run into 
this problem. Long time periods can be selected without problems if only 
exporting the data.</p>

<p>{$interface}</p>

<p><i>Pro Tip:</i> Click the legend name to de/select data series. 
To zoom in, click and drag your mouse within the plot frame.</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site. If
details are not provided below, the site does not have data entered yet
or has issues that need to be resolved first relative to quality
concerns.</p>
<pre>
 ST  SITE       INTERVAL

</pre></p>
EOF;
$t->render('full.phtml');
?>