<?php
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$HIGHCHARTS = "9.3.1";

$site = isset($_GET["site"]) ? $_GET["site"]: 'IA_Boone';
$date = isset($_GET["date"]) ? $_GET["date"]: '2016-06-09';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$ungroup = isset($_GET["ungroup"]) ? $_GET["ungroup"]: '0';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 100;
$by = isset($_GET['by']) ? $_GET['by']: 'daily';

/* 
 with data as (select siteid, min(date),
 max(date) from tile_flow_and_n_loads_data GROUP by siteid)
 
 SELECT '"'||siteid ||  '"=>"' || siteid || ' '||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "IA_Boone"=>"IA_Boone  (2016-06-09 to 2018-12-31) [935 days]",
    "IA_Grundy"=>"IA_Grundy  (2016-09-02 to 2018-12-31) [850 days]",
    "IA_Hamilton1"=>"IA_Hamilton1  (2011-01-01 to 2018-12-31) [2921 days]",
    "IA_Hamilton2"=>"IA_Hamilton2  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Hamilton3"=>"IA_Hamilton3  (2013-06-06 to 2018-12-31) [2034 days]",
    "IA_Story1"=>"IA_Story1  (2016-06-14 to 2018-12-31) [930 days]",
    "IA_Story2"=>"IA_Story2  (2006-01-01 to 2009-12-31) [1460 days]",
    "IA_Tama"=>"IA_Tama  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Washington"=>"IA_Washington  (2007-01-01 to 2017-12-31) [4017 days]",
    "IN_Randolph"=>"IN_Randolph  (2006-06-16 to 2017-12-31) [4216 days]",
    "IN_Tippecanoe"=>"IN_Tippecanoe  (2007-11-04 to 2018-12-31) [4075 days]",
    "MN_Clay1"=>"MN_Clay1  (2013-04-23 to 2018-10-18) [2004 days]",
    "MN_Clay2"=>"MN_Clay2  (2013-04-30 to 2018-09-30) [1979 days]",
    "MN_Redwood1"=>"MN_Redwood1  (2006-01-01 to 2017-12-31) [4382 days]",
    "MN_Redwood3"=>"MN_Redwood3  (2016-07-18 to 2017-10-16) [455 days]",
    "MN_Wilkin1"=>"MN_Wilkin1  (2017-01-01 to 2018-12-31) [729 days]",
    "MN_Wilkin2"=>"MN_Wilkin2  (2017-01-01 to 2018-12-31) [729 days]",
    "MN_Wilkin3"=>"MN_Wilkin3  (2018-01-01 to 2018-12-31) [364 days]",
    "MO_Knox1"=>"MO_Knox1  (2010-07-04 to 2013-12-31) [1276 days]",
    "MO_Knox2"=>"MO_Knox2  (2016-01-01 to 2017-12-31) [730 days]",
    "MO_Knox3"=>"MO_Knox3  (2010-07-06 to 2013-05-23) [1052 days]",
    "MO_Knox4"=>"MO_Knox4  (2010-05-25 to 2013-09-29) [1223 days]",
    "NC_Washington"=>"NC_Washington  (2007-01-01 to 2011-12-31) [1825 days]",
    "ND_Richland"=>"ND_Richland  (2013-04-08 to 2018-12-31) [2093 days]",
    "OH_Auglaize1"=>"OH_Auglaize1  (2008-01-18 to 2014-12-29) [2537 days]",
    "OH_Auglaize2"=>"OH_Auglaize2  (2009-03-25 to 2015-11-20) [2431 days]",
    "OH_Crawford"=>"OH_Crawford  (2008-10-08 to 2014-12-29) [2273 days]",
    "OH_Defiance1"=>"OH_Defiance1  (2008-01-03 to 2014-12-30) [2553 days]",
    "OH_Defiance2"=>"OH_Defiance2  (1999-05-21 to 2008-11-19) [3470 days]",
    "OH_Delaware"=>"OH_Delaware  (2005-01-01 to 2012-12-31) [2921 days]",
    "OH_Fulton"=>"OH_Fulton  (2000-12-07 to 2010-12-20) [3665 days]",
    "OH_Hardin1"=>"OH_Hardin1  (2008-10-02 to 2014-12-29) [2279 days]",
    "OH_Hardin2"=>"OH_Hardin2  (2008-01-01 to 2014-12-29) [2554 days]",
    "OH_Henry"=>"OH_Henry  (2008-01-01 to 2014-12-30) [2555 days]",
    "OH_VanWert"=>"OH_VanWert  (2001-03-12 to 2009-11-10) [3165 days]",
    "SD_Clay"=>"SD_Clay  (2015-01-01 to 2017-12-31) [1095 days]",   
		);
$siteselect = td_site_select("site", $site, $ar);

$jsurl = sprintf("tileflow__%s__%s__%s__%s__%s.js", 
		$site, $date, $days, $by, $ungroup);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;


$t = new MyView();
$t->thispage = "td-tileflow";
$t->title = "TD Tile Flow Data Plotting";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "tileflow_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "discharge_mm";

$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(1990, 0, 1),
		maxDate: new Date(2018, 0, 1)});		

});
</script>
EOF;
$dby = ($by == "daily") ? " CHECKED ": "";
$wby = ($by == "weekly") ? " CHECKED ": "";
$mby = ($by == "monthly") ? " CHECKED ": "";
$yby = ($by == "yearly") ? " CHECKED ": "";
$ungroupselected = ($ungroup == "1") ? " checked=\"checked\"": "";
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Tile Flow Data Plotting</h3>

<p>Tile flow data are included for all applicable sites in this visualization
and aggregation tool. Data are from the USDA-NIFA funded project:
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes"
(Award No. 2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<div class="row">
<div class="col-md-5">
<strong>Site:</strong>
<br />{$siteselect}

</div>
<div class="col-md-3">
<strong>Date:</strong>
<br /><input type="text" id="datepicker" name="date" value="{$date}" size="11">

</div>
<div class="col-md-4">
<strong>Days to Plot:</strong>
<br /><input type="text" name="days" value="{$days}" size="4">
</div>
</div><!-- end row -->

<div class="row">
<div class="col-md-12">
<br /><input type="checkbox" id="ungroup" name="ungroup" value="1"${ungroupselected}>
<label for="ungroup">Show results by plot identifier instead of treatment.</label>

<br /><strong>Sum Values:</strong>
<br />
<input type="radio" name="by" value="daily"{$dby} id="daily"> <label for="daily">daily</label> &nbsp;
<input type="radio" name="by" value="weekly"{$wby} id="weekly">
 <label for="weekly">weekly (Mon-Sun)</label>&nbsp;
<input type="radio" name="by" value="monthly"{$mby} id="monthly"> <label for="monthy">monthly</label> &nbsp;
<input type="radio" name="by" value="yearly"{$yby} id="yearly"> <label for="yearly">yearly</label>

</div>

</div>
<br clear="all" />
<input type="submit" value="Run">
</form>

<p>Plotting of data may not occur if the time period selected is more than 
~700 days. This is due to the amount of data overwhelming the user's web 
browser and failing to load. Select a shorter time span if you run into 
this problem. Long time periods can be selected without problems if only 
exporting the data.</p>

<p><strong>Viewing Options:</strong> Click the legend name to de/select data series. 
To zoom in, click and drag your mouse within the plot frame.</p>

<p><strong>Download Options:</strong> Download the figure by clicking on the
three-bar menu symbol in the upper right corner of the plot.
Download the corresponding data
<a href="/td/dl/#tab_data" target="_blank">here</a>.</p>

<p>{$interface}</p>

EOF;
$t->render('full.phtml');
