<?php
require_once "../../include/require_auth.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$HIGHCHARTS = "8.2.2";

$site = isset($_GET["site"]) ? $_GET["site"]: 'IN_Randolph--NE';
$date = isset($_GET["date"]) ? $_GET["date"]: '2016-06-10';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 100;
$by = isset($_GET['by']) ? $_GET['by']: 'daily';

/* 
 with data as (select siteid, coalesce(plotid, location, '') as pid, min(date),
 max(date) from soil_moisture_data GROUP by siteid, pid)
 
 SELECT '"'||siteid || '--'|| pid || '"=>"' || siteid || ' '||
 pid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "IA_Grundy--"=>"IA_Grundy  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Hamilton1--grass"=>"IA_Hamilton1 grass (2015-01-01 to 2018-12-31) [1460 days]",
    "IA_Hamilton1--next to the control box"=>"IA_Hamilton1 next to the control box (2015-01-01 to 2018-12-31) [1460 days]",
    "IA_Hamilton1--trees"=>"IA_Hamilton1 trees (2015-01-01 to 2018-12-31) [1460 days]",
    "IA_Hamilton3--grass"=>"IA_Hamilton3 grass (2015-01-01 to 2018-12-31) [1460 days]",
    "IA_Hamilton3--next to the control box"=>"IA_Hamilton3 next to the control box (2015-01-01 to 2018-12-31) [1460 days]",
    "IA_Tama--"=>"IA_Tama  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Washington--S1"=>"IA_Washington S1 (2011-06-03 to 2017-12-31) [2403 days]",
    "IA_Washington--S2"=>"IA_Washington S2 (2011-06-07 to 2017-05-03) [2157 days]",
    "IA_Washington--S3"=>"IA_Washington S3 (2011-06-03 to 2017-05-03) [2161 days]",
    "IA_Washington--S4"=>"IA_Washington S4 (2011-06-03 to 2017-12-31) [2403 days]",
    "IA_Washington--S5"=>"IA_Washington S5 (2011-06-03 to 2017-12-31) [2403 days]",
    "IA_Washington--S6"=>"IA_Washington S6 (2011-06-03 to 2017-12-31) [2403 days]",
    "IA_Washington--S7"=>"IA_Washington S7 (2011-06-03 to 2018-02-08) [2442 days]",
    "IA_Washington--S8"=>"IA_Washington S8 (2011-06-03 to 2017-12-31) [2403 days]",
    "IN_Randolph--NE"=>"IN_Randolph NE (2011-07-01 to 2017-10-26) [2309 days]",
    "IN_Randolph--NW"=>"IN_Randolph NW (2011-07-01 to 2017-10-26) [2309 days]",
    "IN_Randolph--SE"=>"IN_Randolph SE (2011-07-01 to 2017-10-26) [2309 days]",
    "IN_Randolph--SW"=>"IN_Randolph SW (2011-07-01 to 2017-10-26) [2309 days]",
    "IN_Tippecanoe--Inlet_A"=>"IN_Tippecanoe Inlet_A (2011-08-02 to 2018-12-31) [2708 days]",
    "IN_Tippecanoe--Inlet_B"=>"IN_Tippecanoe Inlet_B (2011-08-02 to 2015-03-23) [1329 days]",
    "MN_Clay2--CD"=>"MN_Clay2 CD (2012-05-21 to 2018-12-19) [2403 days]",
    "MN_Clay2--SI"=>"MN_Clay2 SI (2012-05-21 to 2015-10-01) [1228 days]",
    "MN_Clay3--UD"=>"MN_Clay3 UD (2015-11-19 to 2018-12-31) [1138 days]",
    "MN_Redwood1--BE"=>"MN_Redwood1 BE (2012-06-08 to 2017-12-31) [2032 days]",
    "MN_Redwood1--BW"=>"MN_Redwood1 BW (2012-06-08 to 2017-12-31) [2032 days]",
    "MN_Redwood2--"=>"MN_Redwood2  (2016-02-06 to 2017-09-25) [597 days]",
    "MN_Redwood3--NPM10"=>"MN_Redwood3 NPM10 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM11"=>"MN_Redwood3 NPM11 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM12"=>"MN_Redwood3 NPM12 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM13"=>"MN_Redwood3 NPM13 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM14"=>"MN_Redwood3 NPM14 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM15"=>"MN_Redwood3 NPM15 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM16"=>"MN_Redwood3 NPM16 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM17"=>"MN_Redwood3 NPM17 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM18"=>"MN_Redwood3 NPM18 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM19"=>"MN_Redwood3 NPM19 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM1"=>"MN_Redwood3 NPM1 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM20"=>"MN_Redwood3 NPM20 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM21"=>"MN_Redwood3 NPM21 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM22"=>"MN_Redwood3 NPM22 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM23"=>"MN_Redwood3 NPM23 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM24"=>"MN_Redwood3 NPM24 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM2"=>"MN_Redwood3 NPM2 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM3"=>"MN_Redwood3 NPM3 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM4"=>"MN_Redwood3 NPM4 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM5"=>"MN_Redwood3 NPM5 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM6"=>"MN_Redwood3 NPM6 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM7"=>"MN_Redwood3 NPM7 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM8"=>"MN_Redwood3 NPM8 (2016-05-17 to 2017-09-29) [500 days]",
    "MN_Redwood3--NPM9"=>"MN_Redwood3 NPM9 (2016-05-17 to 2017-09-29) [500 days]",
    "ND_Richland--West"=>"ND_Richland West (2015-05-22 to 2018-12-31) [1319 days]",
    "OH_Auglaize2--WN"=>"OH_Auglaize2 WN (2011-12-14 to 2015-11-20) [1437 days]",
    "OH_Auglaize2--WS"=>"OH_Auglaize2 WS (2011-09-20 to 2015-11-20) [1522 days]",
    "SD_Clay--Plot7"=>"SD_Clay Plot7 (2016-01-01 to 2017-12-31) [730 days]",
    "SD_Clay--Plot8"=>"SD_Clay Plot8 (2016-01-01 to 2017-12-31) [730 days]",
           );
$siteselect = td_site_select("site", $site, $ar);

$ar = Array(
		'daily' => 'Daily (no aggregation)',
		'monthly' => 'Monthly Averages',
		'yearly' => 'Yearly Averages',
		);
$byselect = make_select("by", $by, $ar);

$jsurl = sprintf("decagon__%s__%s__%s__%s__%s.js", 
    $site, $date, $days, $by, "all");
$jsextra = "<script src=\"{$jsurl}\"></script>";
$interface = <<<EOF
<div id="hc1" style="width: 100%; height: 400px;"></div>
<div id="hc2" style="width: 100%; height: 400px;"></div>
EOF;
	
$t = new MyView();
$t->thispage = "td-soilmoisture";
$t->title = "TD Soil Moisture Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "decagon_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "";
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 0, 1),
		maxDate: new Date(2017, 1, 1)});

    });
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Soil Moisture Data Plotting/Download</h3>

<p>Soil Moisture data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site and Plot:</th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead>
<tr>
    <th>Number of Days to Plot:</th>
    <th>Time-series Aggregation:</th>
</tr>
</thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$byselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>Plotting of data may not occur if the time period selected is more than 
~700 days. This is due to the amount of data overwhelming the user’s web 
browser and failing to load. Select a shorter time span if you run into 
this problem. Long time periods can be selected without problems if only 
exporting the data.</p>

<p>{$interface}</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
<li><strong>What quality control procedures have been implemented?</strong><br />
Please see this <a target="_blank" href="https://docs.google.com/document/d/1K_FtA-nkhCVlkBULgwOpYb4FmMptaZDuEcaqaj7fS-U/edit">Google Drive Doc</a> for more details on this and the flags used
to denote quality control.
</li>
<li><strong>How were data collected?</strong><br />
Variations exist across research sites in methodology and frequency of 
		measurements. Generalized site information is provided below in the table.
		Detailed descriptions are available from the 
		<a target="_blank" href="https://sites.google.com/site/transformingdrainage/database/export-sampling-methods">Transforming Drainage internal website</a>.</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site. If details are
not provided below, the site does not have data entered yet or has issues that need 
to be resolved first relative to quality concerns.</p>
<pre>
 ST  SITE       INTERVAL  SAMPLING DEPTHS [CM]
[IA] BEAR       60 minute  7, 15, 30, 60, 90
[IA] MAASS      5 minute   7, 15, 30, 60, 90
[IA] SERF_IA    5 minute  10, 20, 40, 60, 100
[IN] ACRE       
[IN] DPAC       5 minute  10, 20, 40, 60, 100
[MN] HICKS_B    5 or 60   10, 20, 40, 60, 100
[MN] HICKS.P    
[MN] HICKS.S    
[MN] SWROC      
[ND] CLAY_C     
[ND] CLAY_R     30 minute  5, 15, 30, 45, 60, 75, 90
[ND] CLAY_U     30 minute  5, 15, 30, 45, 60, 75, 90
[ND] FAIRM      30 minute  5, 15, 30, 45, 60, 75, 90
[OH] STJOHNS    5 minute  10, 20, 40, 60, 100
[SD] SERF_SD    daily     10, 20, 40, 60, 100
</pre></p>

<h3>Notes</h3>

<ul>

 <li><strong>DPAC</strong>. Soil moisture is measured at a single location within each quadrant, located midway between a pair of drainage lines, and
selected to be within the zone of influence of the control structure.  It most likely represents the upper end of field soil
moisture.</li>

		<li><strong>HICKS_B</strong> Soil moisture is measured at a single location within each management zone, midway between a pair of drainage lines, and reported to represent the entire zone.</li>
		
		<li><strong>STJOHNS</strong> Soil moisture data at 3 specific locations each in free and managed drainage areas.</li>
 
</ul>


EOF;
$t->render('full.phtml');
?>