<?php
$HIGHCHARTS = "5.0.9";
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';
$errmsg = "";
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';
$varname = isset($_GET["varname"])? $_GET["varname"]: 'AGR17';

/* with data as (select site, min(year),
 max(year) from agronomic_data GROUP by site)
 
 SELECT '"'|| site || '"=>"' || site ||' ('|| min ||' to '|| max ||') ['
 || (max - min) + 1 ||' years]",' as d
 from data ORDER by d;;
*/
$ar = Array(
		//"ACRE"=>"ACRE (2007 to 2007) [1 years]",
		"AUGLA"=>"AUGLA (2008 to 2012) [5 years]",
		"BATH_A"=>"BATH_A (2015 to 2018) [4 years]",
		"CLAY_C"=>"CLAY_C (2012 to 2016) [5 years]",
		"CLAY_R"=>"CLAY_R (2012 to 2016) [5 years]",
		"CLAY_U"=>"CLAY_U (2012 to 2016) [5 years]",
		"CRAWF"=>"CRAWF (2006 to 2011) [6 years]",
		"DEFI_M"=>"DEFI_M (2006 to 2012) [7 years]",
		"DEFI_R"=>"DEFI_R (1997 to 2008) [12 years]",
		"DPAC"=>"DPAC (2005 to 2018) [14 years]",
		"FAIRM"=>"FAIRM (2008 to 2016) [9 years]",
		"FULTON"=>"FULTON (1996 to 2008) [13 years]",
		"HARDIN"=>"HARDIN (2007 to 2012) [6 years]",
		"HARDIN_NW"=>"HARDIN_NW (2006 to 2011) [6 years]",
		"HENRY"=>"HENRY (2006 to 2011) [6 years]",
		"HICKS_B"=>"HICKS_B (2006 to 2018) [13 years]",
		"MUDS1"=>"MUDS1 (2002 to 2018) [17 years]",
		"MUDS2"=>"MUDS2 (2010 to 2017) [8 years]",
		"MUDS3_NEW"=>"MUDS3_NEW (2016 to 2018) [3 years]",
		//"MUDS3_OLD"=>"MUDS3_OLD (2010 to 2013) [4 years]",
		"MUDS4"=>"MUDS4 (2010 to 2013) [4 years]",
		"SERF_IA"=>"SERF_IA (2007 to 2018) [12 years]",
		"SERF_SD"=>"SERF_SD (2016 to 2017) [2 years]",
		"STJOHNS"=>"STJOHNS (2007 to 2015) [9 years]",
		"STORY"=>"STORY (2006 to 2009) [4 years]",
		"SWROC"=>"SWROC (2016 to 2018) [3 years]",
		"TIDE_OLD"=>"TIDE_OLD (2007 to 2012) [6 years]",
		//"UBWC"=>"UBWC (2005 to 2012) [8 years]",
		"VANWERT"=>"VANWERT (1997 to 2008) [12 years]",
		);
$siteselect = make_select("site", $site, $ar);

/**
 select '"'||code_column_heading||'" => "'|| short_description ||'",' from
 cscap_data_dictionary where code_Column_heading ~* 'AGR'
 ORDER by code_column_heading;
 */

$ar = Array(
		"Yield Data" => Array(
				"AGR18" => "Corn grain moisture",
				"AGR17" => "Corn grain yield at 15.5% MB",
				"AGR59" => "Popcorn grain moisture",
				"AGR58" => "Popcorn yield @ 13.5% MB",
				"AGR20" => "Soybean grain moisture",
				"AGR19" => "Soybean grain yield at 13.0% MB",
				"AGR60" => "Sugarbeet yield (root; fresh weight)",
				"AGR22" => "Wheat grain moisture",
				"AGR21" => "Wheat grain yield at 13.5% MB",
				),
		"Biomass Data" => Array(
				"AGR24" => "Corn cob total carbon at R6",
				"AGR26" => "Corn cob total nitrogen at R6",
				"AGR32" => "Corn cob biomass at R6 (dry)",
				"AGR33" => "Corn grain biomass at R6 (dry)",
				"AGR23" => "Corn grain total carbon at R6",
				"AGR25" => "Corn grain total nitrogen at R6",
				"AGR4" => "Corn vegetative biomass at R6 (dry)",
				"AGR9" => "Corn vegetative biomass total carbon at R6",
				"AGR10" => "Corn vegetative biomass total nitrogen at R6",
				"AGR53" => "Forage (cereal rye) biomass",
				"AGR54" => "Forage (cereal rye) biomass total nitrogen",
				"AGR62" => "Forage (sorghum-sudangrass) biomass",
				"AGR63" => "Forage (sorghum-sudangrass) biomass total nitrogen",
				"AGR11" => "Soybean vegetative biomass total carbon at R8",
				"AGR12" => "Soybean vegetative biomass total nitrogen at R8",
				"AGR34" => "Soybean grain biomass at R8 (dry)",
				"AGR27" => "Soybean grain total carbon at R8",
				"AGR28" => "Soybean grain total nitrogen at R8",
				"AGR5" => "Soybean vegetative biomass at R8 (stems and pods only; no leaves)",
				),
		"Misc/Other" => Array(
				"AGR1" => "Corn final plant population",
				"AGR2" => "Soybean final plant population",
				"AGR55" => "Corn Developmental Stage (weekly)",
				"AGR56" => "Leaf Area Index (LAI)",
				"AGR57" => "Normalized Difference Vegetation Index (NDVI)",
				),
		
		);
$varselect = make_select("varname", $varname, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_agronomic.py?site=%s&amp;varname=%s".
			"&amp;ptype=%s&amp;view=%s&amp;group=%s", 
		$site, $varname, $ptype, $view, $group);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("agronomic_%s_%s_%s_%s.js", 
		$site, $varname, $ptype, $group);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

$t = new MyView();
$t->thispage = "td-agronomic";
$t->title = "TD Agronomic Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
});
</script>
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Agronomic Data Plotting/Download</h3>

<p>Agronomic data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead>
<tr>
	<th>Select Site:</th><th>Select Variable</th>
</tr>
</thead>
<tbody>
<tr>
<td>
{$siteselect}
<br /><input type="checkbox" name="group" value="1"${groupselected}> Average plot values by their drainage treatment
</td>
<td>
{$varselect}
</td>
</tr></tbody></table>

<table class="table table-bordered">
<thead>
<tr>
<th>View and Download Options</th></tr></thead>
<tbody><tr>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ul>
<li>Sites vary in the agronomic data collected from each site. Specific
     data types and available years are identified in the Transforming
     Drainage <a target="_blank" href="https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0">master data collected sheet</a>.</li>

<li>Variations exist across research sites in methodology and frequency
     of measurements. Generalized site information is provided below in
     the table. Detailed descriptions are available from the Transforming
     Drainage <a target="_blank" href="https://sites.google.com/site/transformingdrainage/database/export-sampling-methods">internal website</a>.</li>
</ul>

EOF;
$t->render('full.phtml');
?>
