<?php
require_once "../../include/require_auth.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";
$HIGHCHARTS = "6.0.7";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC::NE';
$date = isset($_GET["date"]) ? $_GET["date"]: '2016-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from decagon_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
		"BEAR::grass"=>"BEAR grass (2015-04-16 to 2016-12-31) [625 days]",
		"BEAR::trees"=>"BEAR trees (2015-04-16 to 2016-12-31) [625 days]",
		"CLAY_U::1"=>"CLAY_U 1 (2015-11-19 to 2016-11-25) [372 days]",
		"CLAY_U::2"=>"CLAY_U 2 (2015-11-19 to 2016-11-25) [372 days]",
		"CLAY_R::CD1"=>"CLAY_R CD1 (2012-05-21 to 2017-12-31) [2050 days]",
		"CLAY_R::CD2"=>"CLAY_R CD2 (2012-05-21 to 2017-12-31) [2050 days]",
		"CLAY_R::SI1"=>"CLAY_R SI1 (2012-05-21 to 2015-10-01) [1228 days]",
		"CLAY_R::SI2"=>"CLAY_R SI2 (2012-05-21 to 2015-10-01) [1228 days]",	   
		"DPAC::NE"=>"DPAC NE (2011-07-01 to 2017-10-26) [2309 days]",
		"DPAC::NW"=>"DPAC NW (2011-07-01 to 2017-10-26) [2309 days]",
		"DPAC::SE"=>"DPAC SE (2011-07-01 to 2017-10-26) [2309 days]",
		"DPAC::SW"=>"DPAC SW (2011-07-01 to 2017-10-26) [2309 days]",	   
		"FAIRM::North"=>"FAIRM North (2015-05-22 to 2017-12-31) [954 days]",
		"FAIRM::South"=>"FAIRM South (2015-05-22 to 2017-12-31) [954 days]",	   
		"HICKS_B::E"=>"HICKS_B E (2012-06-08 to 2016-02-17) [1349 days]",
		"HICKS_B::W"=>"HICKS_B W (2012-06-08 to 2016-02-17) [1349 days]",
		"MAASS::1"=>"MAASS 1 (2015-01-01 to 2017-01-03) [733 days]",
		"SERF_IA::1"=>"SERF_IA 1 (2016-01-01 to 2017-12-31) [730 days]",
		"SERF_IA::2"=>"SERF_IA 2 (2016-01-01 to 2017-05-03) [488 days]",
		"SERF_IA::3"=>"SERF_IA 3 (2016-01-01 to 2017-05-03) [488 days]",
		"SERF_IA::4"=>"SERF_IA 4 (2015-12-02 to 2017-12-31) [760 days]",
		"SERF_IA::5"=>"SERF_IA 5 (2015-12-02 to 2017-12-31) [760 days]",
		"SERF_IA::6"=>"SERF_IA 6 (2015-12-02 to 2017-12-31) [760 days]",
		"SERF_IA::7"=>"SERF_IA 7 (2000-01-02 to 2018-03-14) [6646 days]",
		"SERF_IA::8"=>"SERF_IA 8 (2015-12-02 to 2017-12-31) [760 days]",
		"SERF_SD::7"=>"SERF_SD 7 (2016-01-01 to 2016-12-31) [365 days]",
		"SERF_SD::8"=>"SERF_SD 8 (2016-01-01 to 2016-12-31) [365 days]",	   
		"STJOHNS::WN1"=>"STJOHNS WN1 (2011-12-14 to 2015-11-20) [1437 days]",
		"STJOHNS::WN2"=>"STJOHNS WN2 (2011-12-14 to 2015-11-20) [1437 days]",
		"STJOHNS::WN3"=>"STJOHNS WN3 (2011-12-15 to 2015-11-03) [1419 days]",
		"STJOHNS::WS1"=>"STJOHNS WS1 (2011-12-15 to 2015-11-20) [1436 days]",
		"STJOHNS::WS2"=>"STJOHNS WS2 (2011-09-20 to 2015-11-20) [1522 days]",
		"STJOHNS::WS3"=>"STJOHNS WS3 (2011-12-15 to 2015-11-20) [1436 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$ar = Array(
		'all' => 'All Depths, one plot',
		'1' => '10cm, all plots for site',
		'2' => '20cm, all plots for site',
		'3' => '40cm, all plots for site',
		'4' => '60cm, all plots for site',
		'5' => '100cm, all plots for site',
		);
$depthselect = make_select('depth', $depth, $ar);

if ($view != 'plot'){
	$imageurl = sprintf("plot_decagon.py?site=%s&date=%s&days=%s&ptype=%s&view=%s&depth=%s", 
		$site, $date, $days, $ptype, $view, $depth);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
	$jsextra = "";
} else {
	$jsurl = sprintf("decagon_%s_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype, $depth);
    $jsextra = "<script src=\"{$jsurl}\"></script>";
    $interface = <<<EOF
<div id="hc1" style="width: 100%; height: 400px;"></div>
<div id="hc2" style="width: 100%; height: 400px;"></div>
EOF;
	
	
}
$t = new MyView();
$t->thispage = "td-soilmoisture";
$t->title = "TD Soil Moisture Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "decagon_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "";
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 0, 1),
		maxDate: new Date(2017, 1, 1)});		
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Soil Moisture Data Plotting/Download</h3>

<p>Soil Moisture data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site and Plot:</th><th>Depth Option:</th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td><td>{$depthselect}</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Time-series Aggregation:</th><th>View and Download Options</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>Plotting of data may not occur if the time period selected is more than 
~700 days. This is due to the amount of data overwhelming the user’s web 
browser and failing to load. Select a shorter time span if you run into 
this problem. Long time periods can be selected without problems if only 
exporting the data.</p>

<p>{$interface}</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
<li><strong>What quality control procedures have been implemented?</strong><br />
Please see this <a target="_blank" href="https://docs.google.com/document/d/1K_FtA-nkhCVlkBULgwOpYb4FmMptaZDuEcaqaj7fS-U/edit">Google Drive Doc</a> for more details on this and the flags used
to denote quality control.
</li>
<li><strong>How were data collected?</strong><br />
Variations exist across research sites in methodology and frequency of 
		measurements. Generalized site information is provided below in the table.
		Detailed descriptions are available from the 
		<a target="_blank" href="https://sites.google.com/site/transformingdrainage/database/export-sampling-methods">Transforming Drainage internal website</a>.</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site. If details are
not provided below, the site does not have data entered yet or has issues that need 
to be resolved first relative to quality concerns.</p>
<pre>
 ST  SITE       INTERVAL  SAMPLING DEPTHS [CM]
[IA] BEAR       60 minute  7, 15, 30, 60, 90
[IA] MAASS      5 minute   7, 15, 30, 60, 90
[IA] SERF_IA    5 minute  10, 20, 40, 60, 100
[IN] ACRE       
[IN] DPAC       5 minute  10, 20, 40, 60, 100
[MN] HICKS_B    5 or 60   10, 20, 40, 60, 100
[MN] HICKS.P    
[MN] HICKS.S    
[MN] SWROC      
[ND] CLAY_C     
[ND] CLAY_R     30 minute  5, 15, 30, 45, 60, 75, 90
[ND] CLAY_U     30 minute  5, 15, 30, 45, 60, 75, 90
[ND] FAIRM      30 minute  5, 15, 30, 45, 60, 75, 90
[OH] STJOHNS    5 minute  10, 20, 40, 60, 100
[SD] SERF_SD    daily     10, 20, 40, 60, 100
</pre></p>

<h3>Notes</h3>

<ul>

 <li><strong>DPAC</strong>. Soil moisture is measured at a single location within each quadrant, located midway between a pair of drainage lines, and
selected to be within the zone of influence of the control structure.  It most likely represents the upper end of field soil
moisture.</li>

		<li><strong>HICKS_B</strong> Soil moisture is measured at a single location within each management zone, midway between a pair of drainage lines, and reported to represent the entire zone.</li>
		
		<li><strong>STJOHNS</strong> Soil moisture data at 3 specific locations each in free and managed drainage areas.</li>
 
</ul>


EOF;
$t->render('full.phtml');
?>