<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'IA_Boone';
$date = isset($_GET["date"]) ? $_GET["date"]: '2016-06-09';
$by = isset($_GET['by']) ? $_GET['by']: 'daily';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';

$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1000;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/*
 with data as (select siteid, min(date),
 max(date) from tile_flow_and_n_loads_data GROUP by siteid)
 
 SELECT '"'|| siteid || '"=>"' || siteid || '  ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "IA_Boone"=>"IA_Boone  (2016-06-09 to 2018-12-31) [935 days]",
    "IA_Grundy"=>"IA_Grundy  (2016-09-02 to 2018-12-31) [850 days]",
    "IA_Hamilton1"=>"IA_Hamilton1  (2011-01-01 to 2018-12-31) [2921 days]",
    "IA_Hamilton2"=>"IA_Hamilton2  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Hamilton3"=>"IA_Hamilton3  (2013-06-06 to 2018-12-31) [2034 days]",
    "IA_Story1"=>"IA_Story1  (2016-05-06 to 2018-12-31) [969 days]",
    "IA_Story2"=>"IA_Story2  (2006-01-01 to 2009-12-31) [1460 days]",
    "IA_Tama"=>"IA_Tama  (2016-01-01 to 2018-12-31) [1095 days]",
    "IA_Washington"=>"IA_Washington  (2007-01-01 to 2017-12-31) [4017 days]",
    "IN_Randolph"=>"IN_Randolph  (2006-01-01 to 2017-12-31) [4382 days]",
    "IN_Tippecanoe"=>"IN_Tippecanoe  (2007-11-04 to 2018-12-31) [4075 days]",
    "MN_Clay1"=>"MN_Clay1  (2013-04-23 to 2018-10-18) [2004 days]",
    "MN_Clay2"=>"MN_Clay2  (2013-04-30 to 2018-09-30) [1979 days]",
    "MN_Redwood1"=>"MN_Redwood1  (2006-01-01 to 2017-12-31) [4382 days]",
    "MN_Redwood3"=>"MN_Redwood3  (2016-01-01 to 2017-12-31) [730 days]",
    "MN_Wilkin1"=>"MN_Wilkin1  (2017-01-01 to 2018-12-31) [729 days]",
    "MN_Wilkin2"=>"MN_Wilkin2  (2017-01-01 to 2018-12-31) [729 days]",
    "MN_Wilkin3"=>"MN_Wilkin3  (2018-01-01 to 2018-12-31) [364 days]",
    "MO_Knox1"=>"MO_Knox1  (2010-07-04 to 2013-12-31) [1276 days]",
    "MO_Knox2"=>"MO_Knox2  (2016-01-01 to 2017-12-31) [730 days]",
    "MO_Knox3"=>"MO_Knox3  (2010-07-06 to 2013-12-31) [1274 days]",
    "MO_Knox4"=>"MO_Knox4  (2010-05-25 to 2013-12-31) [1316 days]",
    "NC_Washington"=>"NC_Washington  (2007-01-01 to 2011-12-31) [1825 days]",
    "ND_Richland"=>"ND_Richland  (2013-04-08 to 2018-12-31) [2093 days]",
    "OH_Auglaize1"=>"OH_Auglaize1  (2008-01-18 to 2014-12-31) [2539 days]",
    "OH_Auglaize2"=>"OH_Auglaize2  (2009-01-01 to 2015-12-31) [2555 days]",
    "OH_Crawford"=>"OH_Crawford  (2008-10-08 to 2014-12-31) [2275 days]",
    "OH_Defiance1"=>"OH_Defiance1  (2008-01-01 to 2014-12-31) [2556 days]",
    "OH_Defiance2"=>"OH_Defiance2  (1999-05-21 to 2008-11-19) [3470 days]",
    "OH_Delaware"=>"OH_Delaware  (2005-01-01 to 2012-12-31) [2921 days]",
    "OH_Fulton"=>"OH_Fulton  (2000-12-07 to 2011-01-01) [3677 days]",
    "OH_Hardin1"=>"OH_Hardin1  (2008-01-01 to 2014-12-31) [2556 days]",
    "OH_Hardin2"=>"OH_Hardin2  (2008-01-01 to 2014-12-31) [2556 days]",
    "OH_Henry"=>"OH_Henry  (2008-01-01 to 2014-12-31) [2556 days]",
    "OH_VanWert"=>"OH_VanWert  (2001-03-08 to 2009-11-10) [3169 days]",
    "SD_Clay"=>"SD_Clay  (2015-01-01 to 2017-12-31) [1095 days]",
	);
$siteselect = make_select("site", $site, $ar);


$jsurl = sprintf("nitrateload_%s_%s_%s_%s_%s.js", 
    $site, $date, $days, $by, $group);
$jsextra = "<script src=\"{$jsurl}\"></script>";
$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;

$dby = ($by == "daily") ? " CHECKED ": "";
$mby = ($by == "monthly") ? " CHECKED ": "";
$yby = ($by == "yearly") ? " CHECKED ": "";
$t = new MyView();
$t->thispage = "td-nitrateload";
$t->title = "TD Nitrate Load Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/4.2.7/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.7/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.7/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(1990, 0, 1),
		maxDate: new Date(2018, 0, 1)});
});
</script>
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>
<p>&nbsp;</p>
<h3>Nitrate Load Data Plotting/Download</h3>

<p>Nitrate Load data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">

<h4>SELECT</h4>

<div class="row">
<div class="col-md-5">
<strong>Site:</strong>
<br />{$siteselect}

</div>
<div class="col-md-3">
<strong>Date:</strong>
<br /><input type="text" id="datepicker" name="date" value="{$date}" size="11">

</div>
<div class="col-md-4">
<strong>Days to Plot:</strong>
<br /><input type="text" name="days" value="{$days}" size="4">
</div>

</div>

<h4>AGGREGATE</h4>

<div class="row">
<div class="col-md-6">
<strong>Average Plot Values:</strong>
<br /><input type="checkbox" name="group" value="1"${groupselected}> by drainage treatment (not working yet)

</div>
<div class="col-md-6">
<strong>Sum Values:</strong>
<br />
<input type="radio" name="by" value="daily"{$dby}> daily &nbsp;
<input type="radio" name="by" value="monthly"{$mby}> monthly &nbsp;
<input type="radio" name="by" value="yearly"{$yby}> yearly

</div>

</div>
<br clear="all" />
<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> Click the legend name to de/select data series. 
To zoom in, click and drag your mouse within the plot frame.</p>


EOF;
$t->render('full.phtml');
?>
