<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC::NE';
$date = isset($_GET["date"]) ? $_GET["date"]: '2016-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from decagon_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
		"BEAR::grass"=>"BEAR grass (2015-04-16 to 2016-12-31) [625 days]",
		"BEAR::trees"=>"BEAR trees (2015-04-16 to 2016-12-31) [625 days]",
		"CLAY_U::1"=>"CLAY_U 1 (2015-11-19 to 2016-11-25) [372 days]",
		"CLAY_U::2"=>"CLAY_U 2 (2015-11-19 to 2016-11-25) [372 days]",
		"CLAY_R::CD1"=>"CLAY_R CD1 (2012-05-21 to 2016-11-25) [1649 days]",
		"CLAY_R::CD2"=>"CLAY_R CD2 (2012-05-21 to 2016-11-25) [1649 days]",
		"CLAY_R::SI1"=>"CLAY_R SI1 (2012-05-21 to 2015-10-01) [1228 days]",
		"CLAY_R::SI2"=>"CLAY_R SI2 (2012-05-21 to 2015-10-01) [1228 days]",
		"DPAC::NE"=>"DPAC NE (2011-07-01 to 2016-12-21) [2000 days]",
		"DPAC::NW"=>"DPAC NW (2011-07-01 to 2016-12-22) [2001 days]",
		"DPAC::SE"=>"DPAC SE (2011-07-01 to 2016-12-21) [2000 days]",
		"DPAC::SW"=>"DPAC SW (2011-07-01 to 2016-12-21) [2000 days]",
		"FAIRM::1"=>"FAIRM 1 (2015-05-22 to 2016-11-22) [550 days]",
		"FAIRM::2"=>"FAIRM 2 (2015-05-22 to 2016-11-22) [550 days]",
		"MAASS::1"=>"MAASS 1 (2015-01-01 to 2017-01-03) [733 days]",
		"SERF_IA::1"=>"SERF_IA 1 (2016-01-01 to 2016-05-20) [140 days]",
		"SERF_IA::2"=>"SERF_IA 2 (2016-01-01 to 2016-05-20) [140 days]",
		"SERF_IA::3"=>"SERF_IA 3 (2016-01-01 to 2016-05-20) [140 days]",
		"SERF_IA::4"=>"SERF_IA 4 (2015-12-02 to 2016-05-20) [170 days]",
		"SERF_IA::5"=>"SERF_IA 5 (2015-12-02 to 2016-05-20) [170 days]",
		"SERF_IA::6"=>"SERF_IA 6 (2015-12-02 to 2016-05-20) [170 days]",
		"SERF_IA::7"=>"SERF_IA 7 (2000-01-02 to 2016-05-20) [5983 days]",
		"SERF_IA::8"=>"SERF_IA 8 (2015-12-02 to 2016-05-20) [170 days]",
		"SERF_SD::7"=>"SERF_SD 7 (2016-01-01 to 2016-12-31) [365 days]",
		"SERF_SD::8"=>"SERF_SD 8 (2016-01-01 to 2016-12-31) [365 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$ar = Array(
		'all' => 'All Depths, one plot',
		'1' => '10cm, all plots for site',
		'2' => '20cm, all plots for site',
		'3' => '40cm, all plots for site',
		'4' => '60cm, all plots for site',
		'5' => '100cm, all plots for site',
		);
$depthselect = make_select('depth', $depth, $ar);

if ($view != 'plot'){
	$imageurl = sprintf("plot_decagon.py?site=%s&date=%s&days=%s&ptype=%s&view=%s&depth=%s", 
		$site, $date, $days, $ptype, $view, $depth);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
	$jsextra = "";
} else {
	$jsurl = sprintf("decagon_%s_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype, $depth);
    $jsextra = "<script src=\"{$jsurl}\"></script>";
    include_once "../../include/hceditor.php";
    $interface = <<<EOF
<div id="hc1" style="width: 100%; height: 400px;"></div>
<div id="hc2" style="width: 100%; height: 400px;"></div>
{$hceditor}
EOF;
	
	
}
$t = new MyView();
$t->thispage = "td-decagon";
$t->title = "TD Decagon Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.4/modules/exporting.js"></script>
<script src="/js/hceditor.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "decagon_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "";
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2011, 0, 1),
		maxDate: new Date(2017, 1, 1)});		
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Decagon Data Plotting/Download</h3>

<p>Decagon data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site and Plot:</th><th>Depth Option:</th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td><td>{$depthselect}</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View Option</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
<li><strong>What quality control procedures have been implemented?</strong><br />
Please see this <a href="https://docs.google.com/document/d/1K_FtA-nkhCVlkBULgwOpYb4FmMptaZDuEcaqaj7fS-U/edit">Google Drive Doc</a> for more details on this and the flags used
to denote quality control.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE       INTERVAL  SAMPLING DEPTHS     PERIOD
[IN] DPAC       5 minute  10 20 40 60 100 cm  
</pre></p>

<h3>Notes</h3>

<ul>

 <li><strong>DPAC</strong>. Soil moisture is measured at a single location within each quadrant, located midway between a pair of drainage lines, and
selected to be within the zone of influence of the control structure.  It most likely represents the upper end of field soil
moisture.</li>

 
</ul>


EOF;
$t->render('full.phtml');
?>