<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-06-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 1;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, min(date(valid)),
 max(date(valid)) from watertable_data GROUP by uniqueid)
 
 SELECT '"'||uniqueid ||'"=>"' || uniqueid || ' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;

*/
$ar = Array(
		"BEAR"=>"BEAR (2011-01-01 to 2016-11-10) [2140 days]",
		"CLAY_C"=>"CLAY_C (2012-11-07 to 2016-10-27) [1450 days]",
		"CLAY_R"=>"CLAY_R (2012-11-07 to 2016-11-17) [1471 days]",
		"CLAY_U"=>"CLAY_U (2012-11-07 to 2016-10-18) [1441 days]",
		"DEFI_R"=>"DEFI_R (2003-09-23 to 2007-12-06) [1535 days]",
    "DPAC"=>"DPAC (2006-07-01 to 2016-12-14) [3819 days]",
		"FAIRM"=>"FAIRM (2014-05-17 to 2016-11-22) [920 days]",
		"HICKS_B"=>"HICKS_B (2015-06-15 to 2016-10-24) [497 days]",
		"MAASS"=>"MAASS (2014-01-01 to 2016-11-10) [1044 days]",
		"SERF_IA"=>"SERF_IA (2010-12-31 to 2015-12-31) [1826 days]",
		"SERF_SD"=>"SERF_SD (2016-04-20 to 2016-11-04) [198 days]",
		"STJOHNS"=>"STJOHNS (2011-01-13 to 2015-11-20) [1772 days]",
		"TIDE_OLD"=>"TIDE_OLD (2007-01-02 to 2012-12-31) [2190 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'3' => 'Hourly Averages',
		'2' => 'Daily Averages',
		'4' => 'Weekly Averages',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_watertable.py?site=%s&date=%s&days=%s&ptype=%s&view=%s&amp;group=%s", 
		$site, $date, $days, $ptype, $view, $group);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("watertable_%s_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype, $group);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

$t = new MyView();
$t->thispage = "td-watertable";
$t->title = "TD Water Table Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" /> 
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" /> 
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.4/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.4/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(2006, 0, 1),
		maxDate: new Date(2016, 1, 1)});		
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Water Table Data Plotting/Download</h3>

<p>Water Table Depth data included on this page are associated with the project:
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site:</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
<br /><input type="checkbox" name="group" value="1"${groupselected}> Average plot values by their drainage treatment
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Time-series Aggregation:</th><th>View and Download Options</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> Click the legend name to de/select data series. 
To zoom in, click and drag your mouse within the plot frame.</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site. If
details are not provided below, the site does not have data entered yet
or has issues that need to be resolved first relative to quality
concerns.</p>
<pre>
 ST  SITE       INTERVAL
[IA] SERF_IA    60 MIN
[IA] BEAR       DAILY
[IA] MAASS      DAILY
[IN] ACRE       
[IN] DPAC       60 MIN
[IN] HICKS_B    60 MIN
[IN] HICKS_P 
[MN] SWROC      
[NC] BATH_A  
[NC] TIDE_OLD   60 MIN
[ND] CLAY_C     60 MIN
[ND] CLAY_R     60 MIN
[ND] CLAY_U     60 MIN
[NC] FAIRM      30 MIN
[OH] DEFI_R     15 MIN
[OH] STJOHNS    15 MIN
[SD] SERF_SD    15 MIN

</pre></p>
EOF;
$t->render('full.phtml');
?>