<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";
$HIGHCHARTS = "6.0.7";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-01-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 100;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, min(date(valid)),
 max(date(valid)) from tileflow_data GROUP by uniqueid)
 
 SELECT '"'||uniqueid ||  '"=>"' || uniqueid || ' '||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "AUGLA"=>"AUGLA  (2008-05-01 to 2014-12-29) [2433 days]",
    "CLAY_C"=>"CLAY_C  (2015-04-20 to 2015-11-06) [200 days]",
    "CLAY_R"=>"CLAY_R  (2015-04-27 to 2015-12-15) [232 days]",
    "CRAWF"=>"CRAWF  (2008-10-02 to 2014-12-29) [2279 days]",
    "DEFI_R"=>"DEFI_R  (1999-05-21 to 2008-11-19) [3470 days]",
    "DPAC"=>"DPAC  (2011-12-31 to 2016-12-20) [1816 days]",
    "FULTON"=>"FULTON  (2000-12-07 to 2011-03-02) [3737 days]",
    "HARDIN"=>"HARDIN  (2008-10-02 to 2014-12-29) [2279 days]",
    "HARDIN_NW"=>"HARDIN_NW  (2008-01-07 to 2014-12-29) [2548 days]",
    "HENRY"=>"HENRY  (2008-05-17 to 2014-12-31) [2419 days]",
    "MUDS2"=>"MUDS2  (2010-07-04 to 2013-10-20) [1204 days]",
    "MUDS3_OLD"=>"MUDS3_OLD  (2010-05-25 to 2013-06-27) [1129 days]",
    "MUDS4"=>"MUDS4  (2010-07-06 to 2013-05-23) [1052 days]",
    "SERF_IA"=>"SERF_IA  (2007-04-20 to 2016-12-09) [3521 days]",
    "SERF_SD"=>"SERF_SD  (2015-04-14 to 2016-11-03) [569 days]",
    "STJOHNS"=>"STJOHNS  (2009-03-25 to 2015-11-20) [2431 days]",
    "STORY"=>"STORY  (2006-01-01 to 2009-12-31) [1460 days]",
    //"UBWC"=>"UBWC  (2005-01-01 to 2012-12-31) [2921 days]",
    "VANWERT"=>"VANWERT  (2001-03-08 to 2009-11-10) [3169 days]",
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'2' => 'Monthly Totals',
		'3' => 'Daily Totals',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_tileflow.py?site=%s&amp;date=%s&amp;days=%s".
			"&amp;ptype=%s&amp;view=%s&amp;group=%s", 
		$site, $date, $days, $ptype, $view, $group);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("tileflow_%s_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype, $group);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	require_once "../../include/hceditor.php";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
${hceditor}
EOF;
}

$t = new MyView();
$t->thispage = "td-tileflow";
$t->title = "TD Tile Flow Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
var EDIT_TABLE = "tileflow_data";
var EDIT_UNIQUEID = "{$site}";
var EDIT_COLUMN = "discharge_mm";

$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(1990, 0, 1),
		maxDate: new Date(2018, 0, 1)});		
});
</script>
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Tile Flow Data Plotting/Download</h3>

<p>Tile Flow data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).  Precipitation data included in this visualization is provided by site personnel from on-site weather
stations. Only tile flow data are currently available for export under "View and Download Options"</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead>
<tr>
	<th>Select Site:</th><th>Select Start Date</th>
</tr>
</thead>
<tbody>
<tr>
<td>
{$siteselect}
<br /><input type="checkbox" name="group" value="1"${groupselected}> Average plot values by their drainage treatment
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Time-series Aggregation:</th><th>View and Download Options</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>Plotting of data may not occur if the time period selected is more than 
~700 days. This is due to the amount of data overwhelming the user’s web 
browser and failing to load. Select a shorter time span if you run into 
this problem. Long time periods can be selected without problems if only 
exporting the data.</p>

<p>{$interface}</p>

<p><i>Pro Tip:</i> Click the legend name to de/select data series. 
To zoom in, click and drag your mouse within the plot frame.</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>

<li><strong>How were data collected?</strong><br />
Variations exist across research sites in methodology and frequency of
measurements. Generalized site information is provided below in the   
table. Detailed descriptions are available from the
<a target="_blank" href="https://sites.google.com/site/transformingdrainage/database/export-sampling-methods">Transforming   
Drainage internal website.</a></li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site. If
details are not provided below, the site does not have data entered yet
or has issues that need to be resolved first relative to quality
concerns.</p>
<pre>
                    TILE FLOW           PRECIPICATION
ST  SITE         INTERVAL  PERIOD    INTERVAL PERIOD
[IA] BEAR
[IA] MAASS
[IA] SERF_IA      5 MIN    2007-2016
[IA] STORY        DAILY    2006-2009
[IN] ACRE
[IN] DPAC         60 MIN   2011-2015
[MN] HICKS_B
[MN] HICKS_S *begins in 2017
[MN] SWROC *begins in 2017
[MO] MUDS2        60 MIN   2010-2013
[MO] MUDS3_NEW
[MO] MUDS3_OLD    60 MIN   2010-2013     
[MO] MUDS4        60 MIN   2010-2013
[NC] BATH_A
[NC] BATH_R
[NC] TIDE_OLD
[ND] CLAY_C       10 MIN   2015
[ND] CLAY_R       10 MIN   2015
[ND] FAIRM
[SD] SERF_SD      60 MIN   2015
[OH] AUGLA
[OH] CRAWF
[OH] DEFI_M
[OH] DEFI_R
[OH] FULTON
[OH] HARDIN
[OH] HARDIN_NW
[OH] HENRY
[OH] STJOHNS      20 MIN   2011-2015
[OH] UBWC
[OH] VANWERT
		
		
</pre></p>

EOF;
$t->render('full.phtml');
?>
