<?php
$HIGHCHARTS = "6.0.7";
require_once "../../include/require_auth.php";
require_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'IA_Story';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$group = isset($_GET["group"]) ? $_GET["group"]: '0';
$errmsg = "";
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';
$varname = isset($_GET["varname"])? $_GET["varname"]: 'crop_yield';

/* 
 with data as (select siteid, min(year),
 max(year) from agronomic_data GROUP by siteid)
 
 SELECT '"'|| siteid || '"=>"' || siteid ||' ('|| min ||' to '|| max ||') ['
 || (max - min) + 1 ||' years]",' as d
 from data ORDER by d;
*/
$ar = Array(
    "IA_Story2"=>"IA_Story2 (2006 to 2009) [4 years]",
    "IA_Washington"=>"IA_Washington (2007 to 2018) [12 years]",
    "IN_Randolph"=>"IN_Randolph (2005 to 2017) [13 years]",
    "IN_Tippecanoe"=>"IN_Tippecanoe (2007 to 2018) [12 years]",
    "MN_Clay1"=>"MN_Clay1 (2012 to 2018) [7 years]",
    "MN_Clay2"=>"MN_Clay2 (2012 to 2018) [7 years]",
    "MN_Clay3"=>"MN_Clay3 (2012 to 2018) [7 years]",
    "MN_Redwood1"=>"MN_Redwood1 (2006 to 2017) [12 years]",
    "MN_Redwood3"=>"MN_Redwood3 (2016 to 2017) [2 years]",
    "MN_Wilkin1"=>"MN_Wilkin1 (2017 to 2018) [2 years]",
    "MN_Wilkin2"=>"MN_Wilkin2 (2017 to 2017) [1 years]",
    "MO_Knox1"=>"MO_Knox1 (2010 to 2017) [8 years]",
    "MO_Knox2"=>"MO_Knox2 (2015 to 2018) [4 years]",
    "MO_Knox3"=>"MO_Knox3 (2011 to 2013) [3 years]",
    "MO_Knox4"=>"MO_Knox4 (2010 to 2013) [4 years]",
    "MO_Shelby"=>"MO_Shelby (2002 to 2018) [17 years]",
    "NC_Washington"=>"NC_Washington (2007 to 2012) [6 years]",
    "ND_Richland"=>"ND_Richland (2012 to 2018) [7 years]",
    "OH_Auglaize1"=>"OH_Auglaize1 (2008 to 2012) [5 years]",
    "OH_Auglaize2"=>"OH_Auglaize2 (2008 to 2015) [8 years]",
    "OH_Crawford"=>"OH_Crawford (2007 to 2011) [5 years]",
    "OH_Defiance1"=>"OH_Defiance1 (2006 to 2012) [7 years]",
    "OH_Defiance2"=>"OH_Defiance2 (1997 to 2008) [12 years]",
    "OH_Fulton"=>"OH_Fulton (1996 to 2008) [13 years]",
    "OH_Hardin1"=>"OH_Hardin1 (2007 to 2012) [6 years]",
    "OH_Hardin2"=>"OH_Hardin2 (2008 to 2011) [4 years]",
    "OH_Henry"=>"OH_Henry (2008 to 2011) [4 years]",
    "OH_VanWert"=>"OH_VanWert (1997 to 2008) [12 years]",
    "SD_Clay"=>"SD_Clay (2016 to 2017) [2 years]",   
		);
$siteselect = make_select("site", $site, $ar);

/**
 select '"'||code_column_heading||'" => "'|| short_description ||'",' from
 cscap_data_dictionary where code_Column_heading ~* 'AGR'
 ORDER by code_column_heading;
 */

$ar = Array(
		"Yield Data" => Array(
				"AGR18" => "Corn grain moisture",
				"AGR17" => "Corn grain yield at 15.5% MB",
				"AGR59" => "Popcorn grain moisture",
				"AGR58" => "Popcorn yield @ 13.5% MB",
				"AGR20" => "Soybean grain moisture",
				"AGR19" => "Soybean grain yield at 13.0% MB",
				"AGR60" => "Sugarbeet yield (root; fresh weight)",
				"AGR22" => "Wheat grain moisture",
				"AGR21" => "Wheat grain yield at 13.5% MB",
				),
		"Biomass Data" => Array(
				"AGR24" => "Corn cob total carbon at R6",
				"AGR26" => "Corn cob total nitrogen at R6",
				"AGR32" => "Corn cob biomass at R6 (dry)",
				"AGR33" => "Corn grain biomass at R6 (dry)",
				"AGR23" => "Corn grain total carbon at R6",
				"AGR25" => "Corn grain total nitrogen at R6",
				"AGR4" => "Corn vegetative biomass at R6 (dry)",
				"AGR9" => "Corn vegetative biomass total carbon at R6",
				"AGR10" => "Corn vegetative biomass total nitrogen at R6",
				"AGR53" => "Forage (cereal rye) biomass",
				"AGR54" => "Forage (cereal rye) biomass total nitrogen",
				"AGR62" => "Forage (sorghum-sudangrass) biomass",
				"AGR63" => "Forage (sorghum-sudangrass) biomass total nitrogen",
				"AGR11" => "Soybean vegetative biomass total carbon at R8",
				"AGR12" => "Soybean vegetative biomass total nitrogen at R8",
				"AGR34" => "Soybean grain biomass at R8 (dry)",
				"AGR27" => "Soybean grain total carbon at R8",
				"AGR28" => "Soybean grain total nitrogen at R8",
				"AGR5" => "Soybean vegetative biomass at R8 (stems and pods only; no leaves)",
				),
		"Misc/Other" => Array(
				"AGR1" => "Corn final plant population",
				"AGR2" => "Soybean final plant population",
				"AGR55" => "Corn Developmental Stage (weekly)",
				"AGR56" => "Leaf Area Index (LAI)",
				"AGR57" => "Normalized Difference Vegetation Index (NDVI)",
				),
		
		);
$varselect = make_select("varname", $varname, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_agronomic.py?site=%s&amp;varname=%s".
			"&amp;ptype=%s&amp;view=%s&amp;group=%s", 
		$site, $varname, $ptype, $view, $group);
	$uri = sprintf("http://datateam.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("agronomic_%s_%s_%s_%s.js", 
		$site, $varname, $ptype, $group);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

$t = new MyView();
$t->thispage = "td-agronomic";
$t->title = "TD Agronomic Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/highcharts-more.js"></script>
<script src="/vendor/highcharts/${HIGHCHARTS}/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
});
</script>
EOF;
$groupselected = ($group == "1") ? " checked=\"checked\"": "";
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>Agronomic Data Plotting/Download</h3>

<p>Agronomic data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead>
<tr>
	<th>Select Site:</th><th>Select Variable</th>
</tr>
</thead>
<tbody>
<tr>
<td>
{$siteselect}
<br /><input type="checkbox" name="group" value="1"${groupselected}> Average plot values by their drainage treatment
</td>
<td>
{$varselect}
</td>
</tr></tbody></table>

<table class="table table-bordered">
<thead>
<tr>
<th>View and Download Options</th></tr>
</thead>
<tbody><tr>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ul>
<li>Sites vary in the agronomic data collected from each site. Specific
     data types and available years are identified in the Transforming
     Drainage <a target="_blank" href="https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0">master data collected sheet</a>.</li>

<li>Variations exist across research sites in methodology and frequency
     of measurements. Generalized site information is provided below in
     the table. Detailed descriptions are available from the Transforming
     Drainage <a target="_blank" href="https://sites.google.com/site/transformingdrainage/database/export-sampling-methods">internal website</a>.</li>
</ul>

EOF;
$t->render('full.phtml');
?>
