<?php
require_once "../../include/require_auth.php";
include_once "../../include/forms.php";
require_once "../../include/myview.php";

$site = isset($_GET["site"]) ? $_GET["site"]: 'DPAC::SW';
$date = isset($_GET["date"]) ? $_GET["date"]: '2014-01-10';
$view = isset($_GET['view']) ? $_GET['view']: 'plot';
$depth = isset($_GET['depth']) ? $_GET['depth']: 'all';
$errmsg = "";
if (strlen($date) != 10){
	$errmsg = "<div class='alert alert-warning'>Invalid Date Specified!</div>";
	$date = '2014-06-10';
}
$days = isset($_GET["days"]) ? intval($_GET["days"]): 100;
$ptype = isset($_GET['ptype']) ? $_GET['ptype']: '1';

/* with data as (select uniqueid, plotid, min(date(valid)),
 max(date(valid)) from tileflow_data GROUP by uniqueid, plotid)
 
 SELECT '"'||uniqueid || '::'|| plotid || '"=>"' || uniqueid || ' '||
 plotid||' ('|| min ||' to '|| max ||') ['|| (max - min) ||' days]",' as d
 from data ORDER by d;
*/
$ar = Array(
		"CLAY_C::FD"=>"CLAY_C (2015-04-20 to 2015-11-06) [200 days]",
		"CLAY_R::SI"=>"CLAY_R (2015-04-27 to 2015-12-15) [232 days]",
		"DPAC::SW"=>"DPAC (2011-12-31 to 2015-11-17) [1417 days]",
		"MUDS2::T103"=>"MUDS2 (2010-07-04 to 2013-10-20) [1204 days]",
		"MUDS3_OLD::T101"=>"MUDS3_OLD (2010-05-25 to 2013-06-27) [1129 days]",
		"MUDS4::T101"=>"MUDS4 (2010-07-06 to 2013-05-23) [1052 days]",
		"SERF_IA::S6"=>"SERF_IA (2011-01-01 to 2015-12-31) [1825 days]",
		"SERF_SD::PLOT7"=>"SERF_SD (2015-01-01 to 2015-12-31) [364 days]",
		"STJOHNS::WN"=>"STJOHNS (2010-12-31 to 2015-12-31) [1826 days]",
		"STORY::T10"=>"STORY (2006-01-01 to 2009-12-31) [1460 days]",
		"UBWC::B2"=>"UBWC (2005-01-01 to 2012-12-31) [2921 days]",
		
		);
$siteselect = make_select("site", $site, $ar);

$ar = Array(
		'1' => 'Observations (no aggregation)',
		'2' => 'Monthly Totals',
		);
$ptypeselect = make_select("ptype", $ptype, $ar);

$ar = Array(
		'plot'=> 'View Plot',
		'html' => 'View Raw Data in HTML Table',
		'csv' => 'Download as CSV File',
		'excel' => 'Download as Excel File'
		);
$viewselect = make_select('view', $view, $ar);

$jsextra = "";
if ($view != 'plot'){
	$imageurl = sprintf("plot_tileflow.py?site=%s&date=%s&days=%s&ptype=%s&view=%s", 
		$site, $date, $days, $ptype, $view);
	$uri = sprintf("http://iem.local/td/%s", $imageurl);
	if ($view == 'html'){
		$data = file_get_contents($uri);
		$interface = $data;
	} else{
		Header(sprintf("Location: /td/%s", $imageurl));
		die();
	}
} else {
	$jsurl = sprintf("tileflow_%s_%s_%s_%s.js", 
		$site, $date, $days, $ptype);
	$jsextra = "<script src=\"{$jsurl}\"></script>";
	$interface = <<<EOF
<div id="hc" style="width: 100%; height: 400px;"></div>
EOF;
}

$t = new MyView();
$t->thispage = "td-tileflow";
$t->title = "TD Tile Flow Data Plotting/Download";
$t->headextra = <<<EOF
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.css" />
<link rel="stylesheet" href="/vendor/jquery-ui/1.11.4/jquery-ui.theme.css" />
EOF;
$t->jsextra = <<<EOF
<script src="/vendor/jquery-ui/1.11.4/jquery-ui.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts.js"></script>
<script src="/vendor/highcharts/4.2.0/highcharts-more.js"></script>
<script src="/vendor/highcharts/4.2.0/modules/exporting.js"></script>
{$jsextra}
<script>
$(document).ready(function(){
	$( "#datepicker" ).datepicker({dateFormat:"yy-mm-dd",
		defaultDate: "{$date}",
		changeMonth: true,
		changeYear: true,
		minDate: new Date(1990, 0, 1),
		maxDate: new Date(2017, 0, 1)});		
});
</script>
EOF;
$t->content =  <<<EOF
<style>
select {
  color: #000;
}
</style>

<h3>TD Tile Flow Data Plotting/Download</h3>

<p>Tile Flow data included in this visualization and aggregation tool are associated with the
USDA-NIFA funded project: 
"Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No.
2015-68007-23193).</p>

{$errmsg}

<form method="GET" name="plot1">
<table class="table table-bordered">
<thead><tr><th>Select Site: (<i>currently, all plots at site are shown on the graph)</i></th><th>Select Start Date</th>
</tr></thead>
<tbody><tr><td>
{$siteselect}
</td>
<td><input type="text" id="datepicker" name="date" value="{$date}" size="11" /></td>
</tr></tbody></table>

<table class="table table-bordered">
<thead><tr><th>Number of Days to Plot</th>
<th>Timeseries Aggregation:</th><th>View Option</th></tr></thead>
<tbody><tr>
<td><input type="text" name="days" value="{$days}" size="4" /></td>
<td>{$ptypeselect}</td>
<td>{$viewselect}</td>
</tr></tbody>
</table>

<input type="submit" value="Run">
</form>

<p>{$interface}</p>

<p><i>Pro Tip:</i> You can click the legend name to toggle showing and hiding
the data series.  You can also mouse click and drag on the plot to zoom it in.
</p>

<h3>Frequently Asked Questions</h3>

<ol>
<li><strong>How are timezones handled?</strong><br />
The timestamps presented should be valid for the local time zone of the sensor
and are daylight saving time aware.  The daily aggregates should compute the
daily summaries in the time zone of the station.
</li>
</ol>

<h3>Observation Site Collection Interval</h3>

<p>This table lists the observation time interval at each site:
<pre>
 ST  SITE         INTERVAL

</pre></p>

EOF;
$t->render('single.phtml');
?>