<?php 
require_once "../../include/require_auth.php";
require_once "../../include/myview.php";

$t = new MyView();
$t->title = "TD Data Usage Agreement";
$t->thispage = "td-usage";
$t->content = <<<EOF
<p>&nbsp;</p>


<h3>Transforming Drainage Research Data (USDA-NIFA Award No. 2015-68007-23193) Usage Agreement</h3>

<p>Please reference this data set in publications as:</p>

<p>Chighladze, G., L.J. Abendroth, D. Herzmann, M. Helmers, L. Ahiablame, B. 
Allred, L. Bowling, L. Brown, N. Fausey, J. Frankenberger, D. Jaynes, X. Jia, 
J. Kjaersgaard, K. King, E. Kladivko, K. Nelson, L. Pease, B. Reinhart, J. 
Strock, and M. Youssef. 2021. Transforming Drainage Research Data (USDA-NIFA 
Award No. 2015-68007-23193). National Agricultural Library - ARS - USDA. 
<a href="https://doi.org/10.15482/USDA.ADC/1521092" target="_blank">https://doi.org/10.15482/USDA.ADC/1521092</a>.
</p>

<p>You are encouraged to contact the Transforming Drainage personnel 
listed above to ensure proper data interpretation and may also consider 
co-authoring with them. You shall have no claim of ownership to any 
intellectual property rights in any part of the data, content, functions, 
features, code, data exploration tools, logos or other intellectual property 
comprising this database.</p>

<p>The coauthors individually and the Transforming Drainage team collectively 
shall NOT be responsible or liable for the accuracy, reliability and 
completeness of any information included in the database nor the 
suitability of its application for a particular purpose. Data users 
are encouraged to notify the coauthors regarding data quality and 
other issues concerning the data, tools, and functionality of this 
website. Contact <a href="mailto:isudata@iastate.edu">isudata@iastate.edu</a> 
with any questions or concerns 
regarding usage and application of the data available at this site.</p>

EOF;
$t->render('single.phtml');

?>
