<?php 
require_once "../../include/require_auth.php";
require_once "../../include/myview.php";

$pgconn = pg_connect("dbname=sustainablecorn host=iemdb-sustainablecorn.local user=nobody");
$table = <<<EOF
<table class="table table-striped table-bordered">
<thead><tr><th>Email</th><th>Last Usage</th><th>Access Level</th></tr></thead>
EOF;
$rs = pg_query($pgconn, "SELECT * from website_users ".
    "WHERE access_level != 1 ORDER by email ASC");
for ($i=0; $row=@pg_fetch_assoc($rs,$i); $i++){
    $table .= sprintf("<tr><td>%s</td><td>%s</td><td>%s</td></tr>\n",
            $row["email"], $row["last_usage"], $row["access_level"]);
}
$table .= "</table>";

$t = new MyView();

$t->content = <<< EOF

<h3>ISU Data Team Administration Tools</h3>
<ul>
 <li><a href="dlreport.phtml?cscap">CSCAP Download Interface Users</a></li>
 <li><a href="dlreport.phtml?td">TD Download Interface Users</a></li>
</ul>

<h3>Authorized Users and Last Access</h3>

{$table}

EOF;
$t->render('single.phtml');
